import React from 'react';
import { AbsoluteFill, OffthreadVideo, Sequence, staticFile } from 'remotion';
import { Captions, ProgressBar } from '../../lib/shorts';
import { KenBurnsImage, StoryVignette } from '../../lib/story';
import { VO } from './vo.gen';

// =============================================================================
// AUTO-GENERATED by tools/make_short.py — "The Cosmic Signal Defying Physics for 35 Years"
// Camera moves + intensity follow the beat grammar (calm -> building -> payoff).
// motion:true beats use real AI video when FAL is configured, Ken Burns otherwise.
// =============================================================================
export const compositionConfig = {
  id: 'AutoThecosmicsignaldefyin',
  durationInSeconds: 36.84,
  fps: 30,
  width: 1080,
  height: 1920,
};

const ACCENT = '#f5d76e';
const TAIL = 20; // frames each beat under-laps the next so the crossfade never gaps

const BEATS = [
  { src: 'projects/auto-25-the-cosmic-radio-signal-repeatin/b00-hook.nasa.jpg', start: 0, end: 120, move: 'push-in', intensity: 0.5, clip: null, fadeIn: 0 },
  { src: 'projects/auto-25-the-cosmic-radio-signal-repeatin/b01-hook.nasa.jpg', start: 120, end: 211, move: 'orbit-left', intensity: 0.5, clip: null, fadeIn: 14 },
  { src: 'projects/auto-25-the-cosmic-radio-signal-repeatin/b02-setup.nasa.jpg', start: 211, end: 314, move: 'orbit-right', intensity: 0.7, clip: null, fadeIn: 14 },
  { src: 'projects/auto-25-the-cosmic-radio-signal-repeatin/b03-setup.nasa.jpg', start: 314, end: 451, move: 'drift-down', intensity: 0.75, clip: null, fadeIn: 14 },
  { src: 'projects/auto-25-the-cosmic-radio-signal-repeatin/b04-quiz.nasa.jpg', start: 451, end: 589, move: 'push-in', intensity: 0.75, clip: null, fadeIn: 14 },
  { src: 'projects/auto-25-the-cosmic-radio-signal-repeatin/b05-reveal.nasa.jpg', start: 589, end: 703, move: 'crash-zoom', intensity: 1.2, clip: null, fadeIn: 14 },
  { src: 'projects/auto-25-the-cosmic-radio-signal-repeatin/b06-twist.nasa.jpg', start: 703, end: 852, move: 'pan-right', intensity: 1.15, clip: null, fadeIn: 14 },
  { src: 'projects/auto-25-the-cosmic-radio-signal-repeatin/b07-twist.nasa.jpg', start: 852, end: 989, move: 'drift-up', intensity: 1.15, clip: null, fadeIn: 14 },
  { src: 'projects/auto-25-the-cosmic-radio-signal-repeatin/b08-loop.nasa.jpg', start: 989, end: 1105, move: 'settle', intensity: 0.7, clip: null, fadeIn: 14 },
] as const;

const AutoThecosmicsignaldefyin: React.FC = () => {
  return (
    <AbsoluteFill style={{ background: '#0b0d12' }}>
      {BEATS.map((b, i) => {
        const isLast = i === BEATS.length - 1;
        const dur = b.end - b.start + (isLast ? 0 : TAIL);
        return (
          <Sequence key={i} from={b.start} durationInFrames={dur}>
            {b.clip ? (
              <OffthreadVideo src={staticFile(b.clip)} muted
                style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
            ) : (
              <KenBurnsImage src={b.src} dur={dur} move={b.move}
                intensity={b.intensity} fadeIn={b.fadeIn} />
            )}
          </Sequence>
        );
      })}
      <StoryVignette strength={0.34} />
      <Captions lines={VO} y={1330} size={54} accent={ACCENT} maxWords={5} plate />
      <ProgressBar color={ACCENT} />
    </AbsoluteFill>
  );
};

export default AutoThecosmicsignaldefyin;
