import React from 'react';
import { AbsoluteFill, OffthreadVideo, Sequence, staticFile } from 'remotion';
import { Captions, ProgressBar } from '../../lib/shorts';
import { KenBurnsImage, StoryVignette } from '../../lib/story';
import { VO } from './vo.gen';

// =============================================================================
// AUTO-GENERATED by tools/make_short.py — "The Lone Planet With 10,000x Earth's Auroras"
// Camera moves + intensity follow the beat grammar (calm -> building -> payoff).
// motion:true beats use real AI video when FAL is configured, Ken Burns otherwise.
// =============================================================================
export const compositionConfig = {
  id: 'AutoTheloneplanetwith10',
  durationInSeconds: 40.81,
  fps: 30,
  width: 1080,
  height: 1920,
};

const ACCENT = '#fda4af';
const TAIL = 20; // frames each beat under-laps the next so the crossfade never gaps

const BEATS = [
  { src: 'projects/auto-13-the-rogue-planet-floating-alone/b00-hook.jpg', start: 0, end: 138, move: 'push-in', intensity: 0.5, clip: null, fadeIn: 0 },
  { src: 'projects/auto-13-the-rogue-planet-floating-alone/b01-hook.nasa.jpg', start: 138, end: 271, move: 'crash-zoom', intensity: 0.5, clip: null, fadeIn: 14 },
  { src: 'projects/auto-13-the-rogue-planet-floating-alone/b02-setup.nasa.jpg', start: 271, end: 394, move: 'orbit-left', intensity: 0.69, clip: null, fadeIn: 14 },
  { src: 'projects/auto-13-the-rogue-planet-floating-alone/b03-setup.nasa.jpg', start: 394, end: 516, move: 'pull-back', intensity: 0.73, clip: null, fadeIn: 14 },
  { src: 'projects/auto-13-the-rogue-planet-floating-alone/b04-quiz.nasa.jpg', start: 516, end: 639, move: 'settle', intensity: 0.75, clip: null, fadeIn: 14 },
  { src: 'projects/auto-13-the-rogue-planet-floating-alone/b05-reveal.nasa.jpg', start: 639, end: 771, move: 'push-in', intensity: 1.2, clip: null, fadeIn: 14 },
  { src: 'projects/auto-13-the-rogue-planet-floating-alone/b06-reveal.nasa.jpg', start: 771, end: 894, move: 'orbit-right', intensity: 1.2, clip: null, fadeIn: 14 },
  { src: 'projects/auto-13-the-rogue-planet-floating-alone/b07-twist.nasa.jpg', start: 894, end: 1027, move: 'drift-up', intensity: 1.15, clip: null, fadeIn: 14 },
  { src: 'projects/auto-13-the-rogue-planet-floating-alone/b08-twist.nasa.jpg', start: 1027, end: 1160, move: 'pan-right', intensity: 1.15, clip: null, fadeIn: 14 },
  { src: 'projects/auto-13-the-rogue-planet-floating-alone/b09-loop.jpg', start: 1160, end: 1224, move: 'drift-down', intensity: 0.7, clip: null, fadeIn: 14 },
] as const;

const AutoTheloneplanetwith10: React.FC = () => {
  return (
    <AbsoluteFill style={{ background: '#0b0d12' }}>
      {BEATS.map((b, i) => {
        const isLast = i === BEATS.length - 1;
        const dur = b.end - b.start + (isLast ? 0 : TAIL);
        return (
          <Sequence key={i} from={b.start} durationInFrames={dur}>
            {b.clip ? (
              <OffthreadVideo src={staticFile(b.clip)} muted
                style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
            ) : (
              <KenBurnsImage src={b.src} dur={dur} move={b.move}
                intensity={b.intensity} fadeIn={b.fadeIn} />
            )}
          </Sequence>
        );
      })}
      <StoryVignette strength={0.34} />
      <Captions lines={VO} y={1330} size={54} accent={ACCENT} maxWords={5} plate />
      <ProgressBar color={ACCENT} />
    </AbsoluteFill>
  );
};

export default AutoTheloneplanetwith10;
