import React from 'react';
import { AbsoluteFill, OffthreadVideo, Sequence, staticFile } from 'remotion';
import { Captions, ProgressBar } from '../../lib/shorts';
import { KenBurnsImage } from '../../lib/story';
import { StatLayer, HookCard } from '../../lib/finance';
import { Transition } from '../../lib/transitions';
import { VO } from './vo.gen';

// =============================================================================
// AUTO-GENERATED by tools/make_short.py (FINANCE edit format) — "The $412 Bank Sweep Trap"
// Dark background plates + kinetic data-graphics (counter/bars/percent/rule),
// hard transitions on every beat change, numbers highlighted in captions.
// =============================================================================
export const compositionConfig = {
  id: 'AutoThe412Banksweeptrap',
  durationInSeconds: 32.74,
  fps: 30,
  width: 1080,
  height: 1920,
};

const ACCENT = '#a78bfa';
const TAIL = 20;

const BEATS = [
  { src: 'projects/fin-4-the-1-8-bank-sweep-trap-why-leav/b00-hook.jpg', start: 0, end: 45, move: 'push-in', intensity: 0.5, clip: null, fadeIn: 0 },
  { src: 'projects/fin-4-the-1-8-bank-sweep-trap-why-leav/b00-hook.jpg', start: 45, end: 101, move: 'pan-right', intensity: 0.42, clip: null, fadeIn: 0 },
  { src: 'projects/fin-4-the-1-8-bank-sweep-trap-why-leav/b01-hook.jpg', start: 101, end: 144, move: 'push-in', intensity: 0.5, clip: null, fadeIn: 14 },
  { src: 'projects/fin-4-the-1-8-bank-sweep-trap-why-leav/b01-hook.jpg', start: 144, end: 196, move: 'pan-right', intensity: 0.42, clip: null, fadeIn: 0 },
  { src: 'projects/fin-4-the-1-8-bank-sweep-trap-why-leav/b02-setup.jpg', start: 196, end: 239, move: 'orbit-left', intensity: 0.69, clip: null, fadeIn: 14 },
  { src: 'projects/fin-4-the-1-8-bank-sweep-trap-why-leav/b02-setup.jpg', start: 239, end: 291, move: 'drift-up', intensity: 0.59, clip: null, fadeIn: 0 },
  { src: 'projects/fin-4-the-1-8-bank-sweep-trap-why-leav/b03-setup.jpg', start: 291, end: 330, move: 'drift-down', intensity: 0.73, clip: null, fadeIn: 14 },
  { src: 'projects/fin-4-the-1-8-bank-sweep-trap-why-leav/b03-setup.jpg', start: 330, end: 378, move: 'pan-left', intensity: 0.62, clip: null, fadeIn: 0 },
  { src: 'projects/fin-4-the-1-8-bank-sweep-trap-why-leav/b04-quiz.jpg', start: 378, end: 421, move: 'settle', intensity: 0.75, clip: null, fadeIn: 14 },
  { src: 'projects/fin-4-the-1-8-bank-sweep-trap-why-leav/b04-quiz.jpg', start: 421, end: 474, move: 'pan-right', intensity: 0.64, clip: null, fadeIn: 0 },
  { src: 'projects/fin-4-the-1-8-bank-sweep-trap-why-leav/b05-quiz.jpg', start: 474, end: 517, move: 'drift-up', intensity: 0.75, clip: null, fadeIn: 14 },
  { src: 'projects/fin-4-the-1-8-bank-sweep-trap-why-leav/b05-quiz.jpg', start: 517, end: 569, move: 'pan-right', intensity: 0.64, clip: null, fadeIn: 0 },
  { src: 'projects/fin-4-the-1-8-bank-sweep-trap-why-leav/b06-reveal.jpg', start: 569, end: 615, move: 'crash-zoom', intensity: 1.2, clip: null, fadeIn: 14 },
  { src: 'projects/fin-4-the-1-8-bank-sweep-trap-why-leav/b06-reveal.jpg', start: 615, end: 672, move: 'settle', intensity: 1.02, clip: null, fadeIn: 0 },
  { src: 'projects/fin-4-the-1-8-bank-sweep-trap-why-leav/b07-reveal.jpg', start: 672, end: 715, move: 'push-in', intensity: 1.2, clip: null, fadeIn: 14 },
  { src: 'projects/fin-4-the-1-8-bank-sweep-trap-why-leav/b07-reveal.jpg', start: 715, end: 767, move: 'pan-right', intensity: 1.02, clip: null, fadeIn: 0 },
  { src: 'projects/fin-4-the-1-8-bank-sweep-trap-why-leav/b08-twist.jpg', start: 767, end: 810, move: 'pull-back', intensity: 1.15, clip: null, fadeIn: 14 },
  { src: 'projects/fin-4-the-1-8-bank-sweep-trap-why-leav/b08-twist.jpg', start: 810, end: 863, move: 'pan-left', intensity: 0.98, clip: null, fadeIn: 0 },
  { src: 'projects/fin-4-the-1-8-bank-sweep-trap-why-leav/b09-loop.jpg', start: 863, end: 917, move: 'push-in', intensity: 0.7, clip: null, fadeIn: 14 },
  { src: 'projects/fin-4-the-1-8-bank-sweep-trap-why-leav/b09-loop.jpg', start: 917, end: 982, move: 'pan-right', intensity: 0.59, clip: null, fadeIn: 0 },
] as const;

const STATS = [
  { graphic: 'counter', value: "$5,400", label: "median checking balance", bars: null, onScreen: "MEDIAN _CHECKING_ BALANCE", from: 0, end: 101 },
  { graphic: 'counter', value: "$412", label: "annual forfeited yield", bars: null, onScreen: "_FORFEITED_ ANNUAL YIELD", from: 101, end: 196 },
  { graphic: 'bars', value: "5.29%", label: "bank yield spread", bars: ["Bank Overnight=5.30", "Your Checking=0.01"], onScreen: "THE _YIELD_ SPREAD", from: 196, end: 291 },
  { graphic: 'counter', value: "5.29%", label: "bank profit margin", bars: null, onScreen: "BANK _PROFIT_ MARGIN", from: 291, end: 378 },
  { graphic: 'counter', value: "CHECK YOUR APP", label: "your idle balance", bars: null, onScreen: "CHECK _YOUR_ APP", from: 378, end: 474 },
  { graphic: 'counter', value: "$0", label: "comment your cash", bars: null, onScreen: "AUDIT _YOUR_ CASH", from: 474, end: 569 },
  { graphic: 'rule', value: "$1,000", label: "max checking floor", bars: null, onScreen: "SET A _CHECKING_ FLOOR", from: 569, end: 672 },
  { graphic: 'percent', value: "5.00%", label: "risk-free yield", bars: null, onScreen: "_RISK-FREE_ REVENUE STREAM", from: 672, end: 767 },
  { graphic: 'percent', value: "0.01%", label: "default sweep rate", bars: null, onScreen: "_DEFAULT_ SWEEP TRAP", from: 767, end: 863 },
  { graphic: 'counter', value: "$412", label: "annual forfeited yield", bars: null, onScreen: "STOP _FORFEITING_ $412", from: 863, end: 982 },
] as const;

const TRANSITIONS = [
  { kind: 'wipe', at: 101, dur: 8 },
  { kind: 'whip-pan', at: 196, dur: 8 },
  { kind: 'glitch', at: 291, dur: 8 },
  { kind: 'whip-pan', at: 378, dur: 8 },
  { kind: 'wipe', at: 474, dur: 8 },
  { kind: 'flash', at: 569, dur: 8 },
  { kind: 'flash', at: 672, dur: 8 },
  { kind: 'glitch', at: 767, dur: 8 },
  { kind: 'wipe', at: 863, dur: 8 },
] as const;

const HOOK_CARD = "THE _$412_ CHECKING TRAP";
const HOOK_END = 101;

const AutoThe412Banksweeptrap: React.FC = () => {
  return (
    <AbsoluteFill style={{ background: '#0a0c10' }}>
      {BEATS.map((b, i) => {
        const isLast = i === BEATS.length - 1;
        const dur = b.end - b.start + (isLast ? 0 : TAIL);
        return (
          <Sequence key={i} from={b.start} durationInFrames={dur}>
            {b.clip ? (
              <OffthreadVideo src={staticFile(b.clip)} muted
                style={{ width: '100%', height: '100%', objectFit: 'cover', filter: 'brightness(0.55)' }} />
            ) : (
              <KenBurnsImage src={b.src} dur={dur} move={b.move}
                intensity={b.intensity} fadeIn={b.fadeIn} />
            )}
          </Sequence>
        );
      })}
      <AbsoluteFill style={{ background: 'rgba(8, 10, 14, 0.5)' }} />
      <Sequence from={0} durationInFrames={HOOK_END + 20}>
        <HookCard text={HOOK_CARD} accent={ACCENT} />
      </Sequence>
      {STATS.map((s, i) => (
        <Sequence key={'s' + i} from={s.from + 6} durationInFrames={s.end - s.from - 6}>
          <StatLayer graphic={s.graphic} value={s.value} label={s.label}
            bars={s.bars} onScreen={s.onScreen} accent={ACCENT} />
        </Sequence>
      ))}
      {TRANSITIONS.map((t, i) => (
        <Sequence key={'t' + i} from={Math.max(0, t.at - 4)} durationInFrames={t.dur}>
          <Transition kind={t.kind} dur={t.dur} accent={ACCENT} />
        </Sequence>
      ))}
      <Captions lines={VO} y={1330} size={54} accent={ACCENT} maxWords={5} plate highlight />
      <ProgressBar color={ACCENT} />
    </AbsoluteFill>
  );
};

export default AutoThe412Banksweeptrap;
