import React from 'react';
import { AbsoluteFill, OffthreadVideo, Sequence, staticFile } from 'remotion';
import { Captions, ProgressBar } from '../../lib/shorts';
import { KenBurnsImage } from '../../lib/story';
import { StatLayer, HookCard } from '../../lib/finance';
import { Transition } from '../../lib/transitions';
import { VO } from './vo.gen';

// =============================================================================
// AUTO-GENERATED by tools/make_short.py (FINANCE edit format) — "The $412 Bank Sweep Trap"
// Dark background plates + kinetic data-graphics (counter/bars/percent/rule),
// hard transitions on every beat change, numbers highlighted in captions.
// =============================================================================
export const compositionConfig = {
  id: 'AutoThe412Banksweeptrap',
  durationInSeconds: 32.8,
  fps: 30,
  width: 1080,
  height: 1920,
};

const ACCENT = '#a78bfa';
const TAIL = 20;

const BEATS = [
  { src: 'projects/fin-3-the-1-8-bank-sweep-trap-why-leav/b00-hook.jpg', start: 0, end: 56, move: 'push-in', intensity: 0.5, clip: null, fadeIn: 0 },
  { src: 'projects/fin-3-the-1-8-bank-sweep-trap-why-leav/b00-hook.jpg', start: 56, end: 125, move: 'pan-right', intensity: 0.42, clip: null, fadeIn: 0 },
  { src: 'projects/fin-3-the-1-8-bank-sweep-trap-why-leav/b01-setup.jpg', start: 125, end: 174, move: 'orbit-left', intensity: 0.65, clip: null, fadeIn: 14 },
  { src: 'projects/fin-3-the-1-8-bank-sweep-trap-why-leav/b01-setup.jpg', start: 174, end: 234, move: 'drift-up', intensity: 0.55, clip: null, fadeIn: 0 },
  { src: 'projects/fin-3-the-1-8-bank-sweep-trap-why-leav/b02-setup.jpg', start: 234, end: 284, move: 'drift-up', intensity: 0.7, clip: null, fadeIn: 14 },
  { src: 'projects/fin-3-the-1-8-bank-sweep-trap-why-leav/b02-setup.jpg', start: 284, end: 344, move: 'pan-right', intensity: 0.59, clip: null, fadeIn: 0 },
  { src: 'projects/fin-3-the-1-8-bank-sweep-trap-why-leav/b03-quiz.jpg', start: 344, end: 389, move: 'settle', intensity: 0.75, clip: null, fadeIn: 14 },
  { src: 'projects/fin-3-the-1-8-bank-sweep-trap-why-leav/b03-quiz.jpg', start: 389, end: 443, move: 'pan-right', intensity: 0.64, clip: null, fadeIn: 0 },
  { src: 'projects/fin-3-the-1-8-bank-sweep-trap-why-leav/b04-quiz.jpg', start: 443, end: 483, move: 'pan-right', intensity: 0.75, clip: null, fadeIn: 14 },
  { src: 'projects/fin-3-the-1-8-bank-sweep-trap-why-leav/b04-quiz.jpg', start: 483, end: 532, move: 'pull-back', intensity: 0.64, clip: null, fadeIn: 0 },
  { src: 'projects/fin-3-the-1-8-bank-sweep-trap-why-leav/b05-reveal.jpg', start: 532, end: 590, move: 'crash-zoom', intensity: 1.2, clip: null, fadeIn: 14 },
  { src: 'projects/fin-3-the-1-8-bank-sweep-trap-why-leav/b05-reveal.jpg', start: 590, end: 662, move: 'settle', intensity: 1.02, clip: null, fadeIn: 0 },
  { src: 'projects/fin-3-the-1-8-bank-sweep-trap-why-leav/b06-reveal.jpg', start: 662, end: 711, move: 'pull-back', intensity: 1.2, clip: null, fadeIn: 14 },
  { src: 'projects/fin-3-the-1-8-bank-sweep-trap-why-leav/b06-reveal.jpg', start: 711, end: 771, move: 'pan-left', intensity: 1.02, clip: null, fadeIn: 0 },
  { src: 'projects/fin-3-the-1-8-bank-sweep-trap-why-leav/b07-twist.jpg', start: 771, end: 820, move: 'orbit-right', intensity: 1.15, clip: null, fadeIn: 14 },
  { src: 'projects/fin-3-the-1-8-bank-sweep-trap-why-leav/b07-twist.jpg', start: 820, end: 880, move: 'drift-down', intensity: 0.98, clip: null, fadeIn: 0 },
  { src: 'projects/fin-3-the-1-8-bank-sweep-trap-why-leav/b08-loop.jpg', start: 880, end: 927, move: 'push-in', intensity: 0.7, clip: null, fadeIn: 14 },
  { src: 'projects/fin-3-the-1-8-bank-sweep-trap-why-leav/b08-loop.jpg', start: 927, end: 984, move: 'pan-right', intensity: 0.59, clip: null, fadeIn: 0 },
] as const;

const STATS = [
  { graphic: 'counter', value: "$412", label: "annual forfeited yield", bars: null, onScreen: "YOUR _CHECKING_ IS LEAKING", from: 0, end: 125 },
  { graphic: 'counter', value: "0.01%", label: "standard checking rate", bars: null, onScreen: "BANK PAYS _0.01%_ YIELD", from: 125, end: 234 },
  { graphic: 'counter', value: "5.00%", label: "overnight lending spread", bars: null, onScreen: "THEY LEND AT _5%_", from: 234, end: 344 },
  { graphic: 'rule', value: "PAUSE AND CHECK BALANCE", label: "check your balance", bars: null, onScreen: "PAUSE AND _CHECK_ BALANCE", from: 344, end: 443 },
  { graphic: 'rule', value: "COMMENT YOUR IDLE CASH", label: "drop your total", bars: null, onScreen: "_COMMENT_ YOUR IDLE CASH", from: 443, end: 532 },
  { graphic: 'rule', value: "$5,000", label: "maximum checking cap", bars: null, onScreen: "CAP CHECKING AT _$5K_", from: 532, end: 662 },
  { graphic: 'bars', value: "4.5%", label: "yield spread comparison", bars: ["High Yield=4.50", "Checking=0.01"], onScreen: "_SWEEP_ THE SPREAD DIFFERENCE", from: 662, end: 771 },
  { graphic: 'counter', value: "$412", label: "bank profit on sweep", bars: null, onScreen: "THEY PROFIT ON _LAZINESS_", from: 771, end: 880 },
  { graphic: 'counter', value: "$412", label: "annual forfeited yield", bars: null, onScreen: "EVERY MONTH _$34_ DISAPPEARS", from: 880, end: 984 },
] as const;

const TRANSITIONS = [
  { kind: 'wipe', at: 125, dur: 8 },
  { kind: 'whip-pan', at: 234, dur: 8 },
  { kind: 'glitch', at: 344, dur: 8 },
  { kind: 'whip-pan', at: 443, dur: 8 },
  { kind: 'flash', at: 532, dur: 8 },
  { kind: 'flash', at: 662, dur: 8 },
  { kind: 'glitch', at: 771, dur: 8 },
  { kind: 'whip-pan', at: 880, dur: 8 },
] as const;

const HOOK_CARD = "THE _$412_ BANK TRAP";
const HOOK_END = 125;

const AutoThe412Banksweeptrap: React.FC = () => {
  return (
    <AbsoluteFill style={{ background: '#0a0c10' }}>
      {BEATS.map((b, i) => {
        const isLast = i === BEATS.length - 1;
        const dur = b.end - b.start + (isLast ? 0 : TAIL);
        return (
          <Sequence key={i} from={b.start} durationInFrames={dur}>
            {b.clip ? (
              <OffthreadVideo src={staticFile(b.clip)} muted
                style={{ width: '100%', height: '100%', objectFit: 'cover', filter: 'brightness(0.55)' }} />
            ) : (
              <KenBurnsImage src={b.src} dur={dur} move={b.move}
                intensity={b.intensity} fadeIn={b.fadeIn} />
            )}
          </Sequence>
        );
      })}
      <AbsoluteFill style={{ background: 'rgba(8, 10, 14, 0.5)' }} />
      <Sequence from={0} durationInFrames={HOOK_END + 20}>
        <HookCard text={HOOK_CARD} accent={ACCENT} />
      </Sequence>
      {STATS.map((s, i) => (
        <Sequence key={'s' + i} from={s.from + 6} durationInFrames={s.end - s.from - 6}>
          <StatLayer graphic={s.graphic} value={s.value} label={s.label}
            bars={s.bars} onScreen={s.onScreen} accent={ACCENT} />
        </Sequence>
      ))}
      {TRANSITIONS.map((t, i) => (
        <Sequence key={'t' + i} from={Math.max(0, t.at - 4)} durationInFrames={t.dur}>
          <Transition kind={t.kind} dur={t.dur} accent={ACCENT} />
        </Sequence>
      ))}
      <Captions lines={VO} y={1330} size={54} accent={ACCENT} maxWords={5} plate highlight />
      <ProgressBar color={ACCENT} />
    </AbsoluteFill>
  );
};

export default AutoThe412Banksweeptrap;
