import React from 'react';
import { AbsoluteFill, OffthreadVideo, Sequence, staticFile } from 'remotion';
import { Captions, ProgressBar } from '../../lib/shorts';
import { KenBurnsImage } from '../../lib/story';
import { StatLayer, HookCard } from '../../lib/finance';
import { Transition } from '../../lib/transitions';
import { VO } from './vo.gen';

// =============================================================================
// AUTO-GENERATED by tools/make_short.py (FINANCE edit format) — "The $412 Bank Sweep Trap"
// Dark background plates + kinetic data-graphics (counter/bars/percent/rule),
// hard transitions on every beat change, numbers highlighted in captions.
// =============================================================================
export const compositionConfig = {
  id: 'AutoThe412Banksweeptrap',
  durationInSeconds: 32.76,
  fps: 30,
  width: 1080,
  height: 1920,
};

const ACCENT = '#a78bfa';
const TAIL = 20;

const BEATS = [
  { src: 'projects/fin-2-the-1-8-bank-sweep-trap-why-leav/b00-hook.jpg', start: 0, end: 55, move: 'push-in', intensity: 0.5, clip: null, fadeIn: 0 },
  { src: 'projects/fin-2-the-1-8-bank-sweep-trap-why-leav/b00-hook.jpg', start: 55, end: 123, move: 'pan-right', intensity: 0.42, clip: null, fadeIn: 0 },
  { src: 'projects/fin-2-the-1-8-bank-sweep-trap-why-leav/b01-setup.jpg', start: 123, end: 172, move: 'drift-down', intensity: 0.65, clip: null, fadeIn: 14 },
  { src: 'projects/fin-2-the-1-8-bank-sweep-trap-why-leav/b01-setup.jpg', start: 172, end: 231, move: 'pan-left', intensity: 0.55, clip: null, fadeIn: 0 },
  { src: 'projects/fin-2-the-1-8-bank-sweep-trap-why-leav/b02-setup.jpg', start: 231, end: 280, move: 'pan-right', intensity: 0.7, clip: null, fadeIn: 14 },
  { src: 'projects/fin-2-the-1-8-bank-sweep-trap-why-leav/b02-setup.jpg', start: 280, end: 340, move: 'pull-back', intensity: 0.59, clip: null, fadeIn: 0 },
  { src: 'projects/fin-2-the-1-8-bank-sweep-trap-why-leav/b03-quiz.jpg', start: 340, end: 385, move: 'settle', intensity: 0.75, clip: null, fadeIn: 14 },
  { src: 'projects/fin-2-the-1-8-bank-sweep-trap-why-leav/b03-quiz.jpg', start: 385, end: 440, move: 'pan-right', intensity: 0.64, clip: null, fadeIn: 0 },
  { src: 'projects/fin-2-the-1-8-bank-sweep-trap-why-leav/b04-quiz.jpg', start: 440, end: 485, move: 'drift-up', intensity: 0.75, clip: null, fadeIn: 14 },
  { src: 'projects/fin-2-the-1-8-bank-sweep-trap-why-leav/b04-quiz.jpg', start: 485, end: 540, move: 'pan-right', intensity: 0.64, clip: null, fadeIn: 0 },
  { src: 'projects/fin-2-the-1-8-bank-sweep-trap-why-leav/b05-reveal.jpg', start: 540, end: 589, move: 'crash-zoom', intensity: 1.2, clip: null, fadeIn: 14 },
  { src: 'projects/fin-2-the-1-8-bank-sweep-trap-why-leav/b05-reveal.jpg', start: 589, end: 649, move: 'settle', intensity: 1.02, clip: null, fadeIn: 0 },
  { src: 'projects/fin-2-the-1-8-bank-sweep-trap-why-leav/b06-reveal.jpg', start: 649, end: 694, move: 'push-in', intensity: 1.2, clip: null, fadeIn: 14 },
  { src: 'projects/fin-2-the-1-8-bank-sweep-trap-why-leav/b06-reveal.jpg', start: 694, end: 749, move: 'pan-right', intensity: 1.02, clip: null, fadeIn: 0 },
  { src: 'projects/fin-2-the-1-8-bank-sweep-trap-why-leav/b07-twist.jpg', start: 749, end: 798, move: 'pull-back', intensity: 1.15, clip: null, fadeIn: 14 },
  { src: 'projects/fin-2-the-1-8-bank-sweep-trap-why-leav/b07-twist.jpg', start: 798, end: 858, move: 'pan-left', intensity: 0.98, clip: null, fadeIn: 0 },
  { src: 'projects/fin-2-the-1-8-bank-sweep-trap-why-leav/b08-loop.jpg', start: 858, end: 914, move: 'push-in', intensity: 0.7, clip: null, fadeIn: 14 },
  { src: 'projects/fin-2-the-1-8-bank-sweep-trap-why-leav/b08-loop.jpg', start: 914, end: 983, move: 'pan-right', intensity: 0.59, clip: null, fadeIn: 0 },
] as const;

const STATS = [
  { graphic: 'counter', value: "8.2%", label: "of your savings", bars: null, onScreen: "YOUR _SAVINGS_ ARE LEAKING", from: 0, end: 123 },
  { graphic: 'counter', value: "0.01%", label: "checking account yield", bars: null, onScreen: "CHECKING PAYS _NOTHING_", from: 123, end: 231 },
  { graphic: 'counter', value: "5.30%", label: "bank overnight rate", bars: null, onScreen: "THEY _LEND_ YOUR CASH", from: 231, end: 340 },
  { graphic: 'counter', value: "CHECK YOUR BALANCE", label: "your idle balance", bars: null, onScreen: "CHECK YOUR _BALANCE_", from: 340, end: 440 },
  { graphic: 'counter', value: "$0", label: "comment your number", bars: null, onScreen: "DROP YOUR _NUMBER_", from: 440, end: 540 },
  { graphic: 'rule', value: "$5,000", label: "max checking balance", bars: null, onScreen: "THE _$5,000_ RULE", from: 540, end: 649 },
  { graphic: 'bars', value: "$412", label: "annual yield spread", bars: ["High Yield=$530", "Checking=$1"], onScreen: "RECOVER _$412_ ANNUALLY", from: 649, end: 749 },
  { graphic: 'percent', value: "98%", label: "bank profit margin", bars: null, onScreen: "BANKS PROFIT ON _INERTIA_", from: 749, end: 858 },
  { graphic: 'counter', value: "8.2%", label: "of your savings", bars: null, onScreen: "THE _8.2%_ LEAK", from: 858, end: 983 },
] as const;

const TRANSITIONS = [
  { kind: 'wipe', at: 123, dur: 8 },
  { kind: 'whip-pan', at: 231, dur: 8 },
  { kind: 'glitch', at: 340, dur: 8 },
  { kind: 'whip-pan', at: 440, dur: 8 },
  { kind: 'flash', at: 540, dur: 8 },
  { kind: 'flash', at: 649, dur: 8 },
  { kind: 'glitch', at: 749, dur: 8 },
  { kind: 'whip-pan', at: 858, dur: 8 },
] as const;

const HOOK_CARD = "THE _8.2%_ LEAK";
const HOOK_END = 123;

const AutoThe412Banksweeptrap: React.FC = () => {
  return (
    <AbsoluteFill style={{ background: '#0a0c10' }}>
      {BEATS.map((b, i) => {
        const isLast = i === BEATS.length - 1;
        const dur = b.end - b.start + (isLast ? 0 : TAIL);
        return (
          <Sequence key={i} from={b.start} durationInFrames={dur}>
            {b.clip ? (
              <OffthreadVideo src={staticFile(b.clip)} muted
                style={{ width: '100%', height: '100%', objectFit: 'cover', filter: 'brightness(0.55)' }} />
            ) : (
              <KenBurnsImage src={b.src} dur={dur} move={b.move}
                intensity={b.intensity} fadeIn={b.fadeIn} />
            )}
          </Sequence>
        );
      })}
      <AbsoluteFill style={{ background: 'rgba(8, 10, 14, 0.5)' }} />
      <Sequence from={0} durationInFrames={HOOK_END + 20}>
        <HookCard text={HOOK_CARD} accent={ACCENT} />
      </Sequence>
      {STATS.map((s, i) => (
        <Sequence key={'s' + i} from={s.from + 6} durationInFrames={s.end - s.from - 6}>
          <StatLayer graphic={s.graphic} value={s.value} label={s.label}
            bars={s.bars} onScreen={s.onScreen} accent={ACCENT} />
        </Sequence>
      ))}
      {TRANSITIONS.map((t, i) => (
        <Sequence key={'t' + i} from={Math.max(0, t.at - 4)} durationInFrames={t.dur}>
          <Transition kind={t.kind} dur={t.dur} accent={ACCENT} />
        </Sequence>
      ))}
      <Captions lines={VO} y={1330} size={54} accent={ACCENT} maxWords={5} plate highlight />
      <ProgressBar color={ACCENT} />
    </AbsoluteFill>
  );
};

export default AutoThe412Banksweeptrap;
