import React from 'react';
import { AbsoluteFill, OffthreadVideo, Sequence, staticFile } from 'remotion';
import { Captions, ProgressBar } from '../../lib/shorts';
import { KenBurnsImage, StoryVignette } from '../../lib/story';
import { VO } from './vo.gen';

// =============================================================================
// AUTO-GENERATED by tools/make_short.py — "The Burning Ice Planet (Gliese 436b)"
// Camera moves + intensity follow the beat grammar (calm -> building -> payoff).
// motion:true beats use real AI video when FAL is configured, Ken Burns otherwise.
// =============================================================================
export const compositionConfig = {
  id: 'AutoTheburningiceplanetg',
  durationInSeconds: 36.84,
  fps: 30,
  width: 1080,
  height: 1920,
};

const ACCENT = '#86efac';
const TAIL = 20; // frames each beat under-laps the next so the crossfade never gaps

const BEATS = [
  { src: 'projects/auto-19-the-planet-made-entirely-of-froz/b00-hook.jpg', start: 0, end: 132, move: 'crash-zoom', intensity: 0.5, clip: null, fadeIn: 0 },
  { src: 'projects/auto-19-the-planet-made-entirely-of-froz/b01-setup.nasa.jpg', start: 132, end: 246, move: 'orbit-left', intensity: 0.65, clip: null, fadeIn: 14 },
  { src: 'projects/auto-19-the-planet-made-entirely-of-froz/b02-setup.nasa.jpg', start: 246, end: 360, move: 'push-in', intensity: 0.7, clip: null, fadeIn: 14 },
  { src: 'projects/auto-19-the-planet-made-entirely-of-froz/b03-quiz.nasa.jpg', start: 360, end: 497, move: 'settle', intensity: 0.75, clip: null, fadeIn: 14 },
  { src: 'projects/auto-19-the-planet-made-entirely-of-froz/b04-reveal.nasa.jpg', start: 497, end: 647, move: 'crash-zoom', intensity: 1.2, clip: null, fadeIn: 14 },
  { src: 'projects/auto-19-the-planet-made-entirely-of-froz/b05-reveal.nasa.jpg', start: 647, end: 772, move: 'push-in', intensity: 1.2, clip: null, fadeIn: 14 },
  { src: 'projects/auto-19-the-planet-made-entirely-of-froz/b06-twist.jpg', start: 772, end: 910, move: 'pull-back', intensity: 1.15, clip: null, fadeIn: 14 },
  { src: 'projects/auto-19-the-planet-made-entirely-of-froz/b07-twist.nasa.jpg', start: 910, end: 1024, move: 'drift-up', intensity: 1.15, clip: null, fadeIn: 14 },
  { src: 'projects/auto-19-the-planet-made-entirely-of-froz/b08-loop.jpg', start: 1024, end: 1105, move: 'settle', intensity: 0.7, clip: null, fadeIn: 14 },
] as const;

const AutoTheburningiceplanetg: React.FC = () => {
  return (
    <AbsoluteFill style={{ background: '#0b0d12' }}>
      {BEATS.map((b, i) => {
        const isLast = i === BEATS.length - 1;
        const dur = b.end - b.start + (isLast ? 0 : TAIL);
        return (
          <Sequence key={i} from={b.start} durationInFrames={dur}>
            {b.clip ? (
              <OffthreadVideo src={staticFile(b.clip)} muted
                style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
            ) : (
              <KenBurnsImage src={b.src} dur={dur} move={b.move}
                intensity={b.intensity} fadeIn={b.fadeIn} />
            )}
          </Sequence>
        );
      })}
      <StoryVignette strength={0.34} />
      <Captions lines={VO} y={1330} size={54} accent={ACCENT} maxWords={5} plate />
      <ProgressBar color={ACCENT} />
    </AbsoluteFill>
  );
};

export default AutoTheburningiceplanetg;
