import React from 'react';
import { AbsoluteFill, OffthreadVideo, Sequence, staticFile } from 'remotion';
import { Captions, ProgressBar } from '../../lib/shorts';
import { KenBurnsImage } from '../../lib/story';
import { StatLayer, HookCard } from '../../lib/finance';
import { Transition } from '../../lib/transitions';
import { VO } from './vo.gen';

// =============================================================================
// AUTO-GENERATED by tools/make_short.py (FINANCE edit format) — "Your Car Payment Is Ruining Your Net Worth"
// Dark background plates + kinetic data-graphics (counter/bars/percent/rule),
// hard transitions on every beat change, numbers highlighted in captions.
// =============================================================================
export const compositionConfig = {
  id: 'AutoYourcarpaymentisruin',
  durationInSeconds: 40.85,
  fps: 30,
  width: 1080,
  height: 1920,
};

const ACCENT = '#a78bfa';
const TAIL = 20;

const BEATS = [
  { src: 'projects/fin-1-your-car-payment-above-10-percen/b00-hook.jpg', start: 0, end: 64, move: 'push-in', intensity: 0.5, clip: null, fadeIn: 0 },
  { src: 'projects/fin-1-your-car-payment-above-10-percen/b00-hook.jpg', start: 64, end: 142, move: 'pan-right', intensity: 0.42, clip: null, fadeIn: 0 },
  { src: 'projects/fin-1-your-car-payment-above-10-percen/b01-setup.jpg', start: 142, end: 209, move: 'drift-up', intensity: 0.65, clip: null, fadeIn: 14 },
  { src: 'projects/fin-1-your-car-payment-above-10-percen/b01-setup.jpg', start: 209, end: 290, move: 'pan-right', intensity: 0.55, clip: null, fadeIn: 0 },
  { src: 'projects/fin-1-your-car-payment-above-10-percen/b02-setup.jpg', start: 290, end: 352, move: 'pan-right', intensity: 0.7, clip: null, fadeIn: 14 },
  { src: 'projects/fin-1-your-car-payment-above-10-percen/b02-setup.jpg', start: 352, end: 427, move: 'pull-back', intensity: 0.59, clip: null, fadeIn: 0 },
  { src: 'projects/fin-1-your-car-payment-above-10-percen/b03-quiz.jpg', start: 427, end: 483, move: 'settle', intensity: 0.75, clip: null, fadeIn: 14 },
  { src: 'projects/fin-1-your-car-payment-above-10-percen/b03-quiz.jpg', start: 483, end: 552, move: 'pan-right', intensity: 0.64, clip: null, fadeIn: 0 },
  { src: 'projects/fin-1-your-car-payment-above-10-percen/b04-reveal.jpg', start: 552, end: 614, move: 'crash-zoom', intensity: 1.2, clip: null, fadeIn: 14 },
  { src: 'projects/fin-1-your-car-payment-above-10-percen/b04-reveal.jpg', start: 614, end: 689, move: 'settle', intensity: 1.02, clip: null, fadeIn: 0 },
  { src: 'projects/fin-1-your-car-payment-above-10-percen/b05-reveal.jpg', start: 689, end: 750, move: 'pull-back', intensity: 1.2, clip: null, fadeIn: 14 },
  { src: 'projects/fin-1-your-car-payment-above-10-percen/b05-reveal.jpg', start: 750, end: 825, move: 'pan-left', intensity: 1.02, clip: null, fadeIn: 0 },
  { src: 'projects/fin-1-your-car-payment-above-10-percen/b06-twist.jpg', start: 825, end: 887, move: 'orbit-left', intensity: 1.15, clip: null, fadeIn: 14 },
  { src: 'projects/fin-1-your-car-payment-above-10-percen/b06-twist.jpg', start: 887, end: 962, move: 'drift-up', intensity: 0.98, clip: null, fadeIn: 0 },
  { src: 'projects/fin-1-your-car-payment-above-10-percen/b07-twist.jpg', start: 962, end: 1018, move: 'drift-down', intensity: 1.15, clip: null, fadeIn: 14 },
  { src: 'projects/fin-1-your-car-payment-above-10-percen/b07-twist.jpg', start: 1018, end: 1087, move: 'pan-left', intensity: 0.98, clip: null, fadeIn: 0 },
  { src: 'projects/fin-1-your-car-payment-above-10-percen/b08-loop.jpg', start: 1087, end: 1150, move: 'push-in', intensity: 0.7, clip: null, fadeIn: 14 },
  { src: 'projects/fin-1-your-car-payment-above-10-percen/b08-loop.jpg', start: 1150, end: 1226, move: 'pan-right', intensity: 0.59, clip: null, fadeIn: 0 },
] as const;

const STATS = [
  { graphic: 'percent', value: "19%", label: "of average paycheck", bars: null, onScreen: "YOUR _PAYCHECK_ IS LEAKING", from: 0, end: 142 },
  { graphic: 'counter', value: "$730", label: "median monthly payment", bars: null, onScreen: "MEDIAN _CAR_ PAYMENT", from: 142, end: 290 },
  { graphic: 'counter', value: "72 mo", label: "average loan length", bars: null, onScreen: "LONGER LOANS _DRAIN_ YOU", from: 290, end: 427 },
  { graphic: 'rule', value: "CALC", label: "payment / net pay", bars: null, onScreen: "DO YOUR _OWN_ MATH", from: 427, end: 552 },
  { graphic: 'rule', value: "20/4/10", label: "auto budget framework", bars: null, onScreen: "THE _20/4/10_ HARD RULE", from: 552, end: 689 },
  { graphic: 'bars', value: "4 yrs", label: "maximum term limit", bars: ["Down Payment=20%", "Max Term=4 yrs", "Max Income=10%"], onScreen: "_CAP_ THE LOAN TERM", from: 689, end: 825 },
  { graphic: 'percent', value: "10%", label: "maximum gross limit", bars: null, onScreen: "HARD _10%_ CEILING", from: 825, end: 962 },
  { graphic: 'counter', value: "84 mo", label: "hidden dealer trap", bars: null, onScreen: "THE _DEALER_ HIDDEN TRAP", from: 962, end: 1087 },
  { graphic: 'percent', value: "19%", label: "of average paycheck", bars: null, onScreen: "_19%_ EATS YOUR FUTURE", from: 1087, end: 1226 },
] as const;

const TRANSITIONS = [
  { kind: 'wipe', at: 142, dur: 8 },
  { kind: 'whip-pan', at: 290, dur: 8 },
  { kind: 'glitch', at: 427, dur: 8 },
  { kind: 'flash', at: 552, dur: 8 },
  { kind: 'flash', at: 689, dur: 8 },
  { kind: 'glitch', at: 825, dur: 8 },
  { kind: 'glitch', at: 962, dur: 8 },
  { kind: 'whip-pan', at: 1087, dur: 8 },
] as const;

const HOOK_CARD = "THE _10%_ CAR TRAP";
const HOOK_END = 142;

const AutoYourcarpaymentisruin: React.FC = () => {
  return (
    <AbsoluteFill style={{ background: '#0a0c10' }}>
      {BEATS.map((b, i) => {
        const isLast = i === BEATS.length - 1;
        const dur = b.end - b.start + (isLast ? 0 : TAIL);
        return (
          <Sequence key={i} from={b.start} durationInFrames={dur}>
            {b.clip ? (
              <OffthreadVideo src={staticFile(b.clip)} muted
                style={{ width: '100%', height: '100%', objectFit: 'cover', filter: 'brightness(0.55)' }} />
            ) : (
              <KenBurnsImage src={b.src} dur={dur} move={b.move}
                intensity={b.intensity} fadeIn={b.fadeIn} />
            )}
          </Sequence>
        );
      })}
      <AbsoluteFill style={{ background: 'rgba(8, 10, 14, 0.5)' }} />
      <Sequence from={0} durationInFrames={HOOK_END + 20}>
        <HookCard text={HOOK_CARD} accent={ACCENT} />
      </Sequence>
      {STATS.map((s, i) => (
        <Sequence key={'s' + i} from={s.from + 6} durationInFrames={s.end - s.from - 6}>
          <StatLayer graphic={s.graphic} value={s.value} label={s.label}
            bars={s.bars} onScreen={s.onScreen} accent={ACCENT} />
        </Sequence>
      ))}
      {TRANSITIONS.map((t, i) => (
        <Sequence key={'t' + i} from={Math.max(0, t.at - 4)} durationInFrames={t.dur}>
          <Transition kind={t.kind} dur={t.dur} accent={ACCENT} />
        </Sequence>
      ))}
      <Captions lines={VO} y={1330} size={54} accent={ACCENT} maxWords={5} plate highlight />
      <ProgressBar color={ACCENT} />
    </AbsoluteFill>
  );
};

export default AutoYourcarpaymentisruin;
