import React from 'react';
import { AbsoluteFill, OffthreadVideo, Sequence, staticFile } from 'remotion';
import { Captions, ProgressBar } from '../../lib/shorts';
import { KenBurnsImage, StoryVignette } from '../../lib/story';
import { VO } from './vo.gen';

// =============================================================================
// AUTO-GENERATED by tools/make_short.py — "A Black Hole Is Creating Stars"
// Camera moves + intensity follow the beat grammar (calm -> building -> payoff).
// motion:true beats use real AI video when FAL is configured, Ken Burns otherwise.
// =============================================================================
export const compositionConfig = {
  id: 'AutoAblackholeiscreating',
  durationInSeconds: 40.82,
  fps: 30,
  width: 1080,
  height: 1920,
};

const ACCENT = '#fda4af';
const TAIL = 20; // frames each beat under-laps the next so the crossfade never gaps

const BEATS = [
  { src: 'projects/auto-23-the-rogue-black-hole-racing-thro/b00-hook.jpg', start: 0, end: 140, move: 'push-in', intensity: 0.5, clip: null, fadeIn: 0 },
  { src: 'projects/auto-23-the-rogue-black-hole-racing-thro/b01-hook.nasa.jpg', start: 140, end: 275, move: 'crash-zoom', intensity: 0.5, clip: null, fadeIn: 14 },
  { src: 'projects/auto-23-the-rogue-black-hole-racing-thro/b02-setup.nasa.jpg', start: 275, end: 401, move: 'drift-up', intensity: 0.69, clip: null, fadeIn: 14 },
  { src: 'projects/auto-23-the-rogue-black-hole-racing-thro/b03-setup.nasa.jpg', start: 401, end: 526, move: 'orbit-right', intensity: 0.73, clip: null, fadeIn: 14 },
  { src: 'projects/auto-23-the-rogue-black-hole-racing-thro/b04-quiz.nasa.jpg', start: 526, end: 661, move: 'pan-right', intensity: 0.75, clip: null, fadeIn: 14 },
  { src: 'projects/auto-23-the-rogue-black-hole-racing-thro/b05-reveal.nasa.jpg', start: 661, end: 795, move: 'push-in', intensity: 1.2, clip: null, fadeIn: 14 },
  { src: 'projects/auto-23-the-rogue-black-hole-racing-thro/b06-reveal.jpg', start: 795, end: 911, move: 'pull-back', intensity: 1.2, clip: null, fadeIn: 14 },
  { src: 'projects/auto-23-the-rogue-black-hole-racing-thro/b07-twist.nasa.jpg', start: 911, end: 1036, move: 'settle', intensity: 1.15, clip: null, fadeIn: 14 },
  { src: 'projects/auto-23-the-rogue-black-hole-racing-thro/b08-twist.nasa.jpg', start: 1036, end: 1161, move: 'orbit-left', intensity: 1.15, clip: null, fadeIn: 14 },
  { src: 'projects/auto-23-the-rogue-black-hole-racing-thro/b09-loop.jpg', start: 1161, end: 1225, move: 'push-in', intensity: 0.7, clip: null, fadeIn: 14 },
] as const;

const AutoAblackholeiscreating: React.FC = () => {
  return (
    <AbsoluteFill style={{ background: '#0b0d12' }}>
      {BEATS.map((b, i) => {
        const isLast = i === BEATS.length - 1;
        const dur = b.end - b.start + (isLast ? 0 : TAIL);
        return (
          <Sequence key={i} from={b.start} durationInFrames={dur}>
            {b.clip ? (
              <OffthreadVideo src={staticFile(b.clip)} muted
                style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
            ) : (
              <KenBurnsImage src={b.src} dur={dur} move={b.move}
                intensity={b.intensity} fadeIn={b.fadeIn} />
            )}
          </Sequence>
        );
      })}
      <StoryVignette strength={0.34} />
      <Captions lines={VO} y={1330} size={54} accent={ACCENT} maxWords={5} plate />
      <ProgressBar color={ACCENT} />
    </AbsoluteFill>
  );
};

export default AutoAblackholeiscreating;
