import React from 'react';
import { AbsoluteFill, Sequence } from 'remotion';
import { Captions, ProgressBar } from '../../lib/shorts';
import { KenBurnsImage, StoryVignette } from '../../lib/story';
import { VO } from './vo.gen';

// =============================================================================
// AUTO-GENERATED by tools/make_short.py — "Earth Built a Nuclear Reactor 2 Billion Years Ago"
// Ken Burns beat images + word-pop captions + progress bar. Local pipeline:
// local-AI script -> Pollinations images -> Kokoro voice -> this render.
// =============================================================================
export const compositionConfig = {
  id: 'AutoEarthbuiltanuclearre',
  durationInSeconds: 36.07,
  fps: 30,
  width: 1080,
  height: 1920,
};

const ACCENT = '#7dd3fc';
const TAIL = 20; // frames each beat under-laps the next so the crossfade never gaps

const BEATS = [
  { src: 'projects/auto-6-the-1-8-billion-year-old-natural/b00-hook.nasa.jpg', start: 6, end: 143, variant: 0, fadeIn: 0 },
  { src: 'projects/auto-6-the-1-8-billion-year-old-natural/b01-setup.nasa.jpg', start: 143, end: 280, variant: 1, fadeIn: 14 },
  { src: 'projects/auto-6-the-1-8-billion-year-old-natural/b02-setup.jpg', start: 280, end: 406, variant: 2, fadeIn: 14 },
  { src: 'projects/auto-6-the-1-8-billion-year-old-natural/b03-quiz.nasa.jpg', start: 406, end: 532, variant: 3, fadeIn: 14 },
  { src: 'projects/auto-6-the-1-8-billion-year-old-natural/b04-reveal.jpg', start: 532, end: 647, variant: 4, fadeIn: 14 },
  { src: 'projects/auto-6-the-1-8-billion-year-old-natural/b05-reveal.nasa.jpg', start: 647, end: 761, variant: 5, fadeIn: 14 },
  { src: 'projects/auto-6-the-1-8-billion-year-old-natural/b06-twist.nasa.jpg', start: 761, end: 875, variant: 0, fadeIn: 14 },
  { src: 'projects/auto-6-the-1-8-billion-year-old-natural/b07-twist.jpg', start: 875, end: 1001, variant: 1, fadeIn: 14 },
  { src: 'projects/auto-6-the-1-8-billion-year-old-natural/b08-loop.nasa.jpg', start: 1001, end: 1082, variant: 2, fadeIn: 14 },
] as const;

const AutoEarthbuiltanuclearre: React.FC = () => {
  return (
    <AbsoluteFill style={{ background: '#0b0d12' }}>
      {BEATS.map((b, i) => {
        const isLast = i === BEATS.length - 1;
        const dur = b.end - b.start + (isLast ? 0 : TAIL);
        return (
          <Sequence key={i} from={b.start} durationInFrames={dur}>
            <KenBurnsImage src={b.src} dur={dur} variant={b.variant} fadeIn={b.fadeIn} />
          </Sequence>
        );
      })}
      <StoryVignette strength={0.34} />
      <Captions lines={VO} y={1330} size={54} accent={ACCENT} maxWords={4} plate />
      <ProgressBar color={ACCENT} />
    </AbsoluteFill>
  );
};

export default AutoEarthbuiltanuclearre;
