#!/usr/bin/env python3
"""
gen_script.py — script.md + beats.json for a short, generated by the LOCAL AI
(the gemini-web2api proxy on 127.0.0.1:8081 — OpenAI-compatible, no API key).

Encodes the repo's six-beat grammar so every generated short follows the
retention-proven structure: HOOK (frame 0 = the thumbnail) -> SETUP -> QUIZ ->
REVEAL -> TWIST -> seamless LOOP (last frame mirrors frame 0). No CTA outros.

The model returns JSON; this tool validates, normalizes timing estimates and
writes the same beats.json contract the TSX track uses (vo[] with beat/text/
imagePrompt + beats[] with visual descriptions), plus a readable script.md.

Usage:
  python tools/gen_script.py --topic "why the sky is blue" --out shorts/auto-1-sky
  python tools/gen_script.py --topic "..." --out ... --style "space documentary" \
      --duration 40 --voice-words 130

.env: LOCAL_AI_BASE_URL (default http://127.0.0.1:8081/v1), LOCAL_AI_MODEL
      (default gemini-3.6-flash).
"""
import argparse
import json
import os
import re
import sys
import urllib.error
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BEAT_GRAMMAR = ["hook", "setup", "quiz", "reveal", "twist", "loop"]
CAMERA_MOVES = ["push-in", "pull-back", "orbit-left", "orbit-right", "drift-up",
                "drift-down", "pan-left", "pan-right", "crash-zoom", "settle"]


def load_env():
    env = {}
    p = os.path.join(ROOT, ".env")
    if os.path.exists(p):
        for line in open(p, encoding="utf-8"):
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            env[k.strip()] = v.strip().strip('"').strip("'")
    return {**env, **os.environ}


def slugify(text, max_len=40):
    s = re.sub(r"[^a-z0-9]+", "-", (text or "").lower()).strip("-")
    return s[:max_len].rstrip("-") or "short"


def extract_json(text):
    """Best-effort JSON extraction (handles ```fences and prose wrappers)."""
    text = re.sub(r"^```(?:json)?|```$", "", text.strip(), flags=re.MULTILINE).strip()
    try:
        return json.loads(text)
    except ValueError:
        pass
    first, last = text.find("{"), text.rfind("}")
    if first != -1 and last > first:
        return json.loads(text[first:last + 1])
    raise ValueError("model response contained no JSON object")


def call_local_ai(prompt, max_tokens=2000, temperature=0.8):
    env = load_env()
    base = env.get("LOCAL_AI_BASE_URL", "http://127.0.0.1:8081/v1").rstrip("/")
    model = env.get("LOCAL_AI_MODEL", "gemini-3.6-flash")
    body = {
        "model": model,
        "messages": [{"role": "user", "content": prompt}],
        "max_tokens": max_tokens,
        "temperature": temperature,
    }
    req = urllib.request.Request(
        f"{base}/chat/completions", data=json.dumps(body).encode("utf-8"),
        headers={"Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=180) as r:
        resp = json.load(r)
    content = resp.get("choices", [{}])[0].get("message", {}).get("content", "")
    if not content.strip():
        raise RuntimeError(f"empty response from local AI ({model} at {base})")
    return content


SYSTEM_PROMPT = """You are a viral short-form video writer. You write scripts for
faceless YouTube Shorts (vertical 9:16, ~30-45s) that follow a strict six-beat
retention grammar AND the winning formula: STRONG BUILD-UP -> POWERFUL PAYOFF ->
NEVER REVEAL EARLY -> ENGAGEMENT TRICKS.

THE FORMULA (non-negotiable):
- NEVER REVEAL EARLY: the hook states the contradiction/mystery, the setup adds
  context, the quiz dares the viewer — but the ANSWER may not appear in the
  hook, setup, or quiz lines in any form (no naming the cause, no giving the
  threshold, no showing the mechanism). The viewer can only learn the answer
  when the reveal beat lands. A hook that spoils the reveal is a broken video.
- STRONG BUILD-UP: every line before the reveal must ESCALATE — each one raises
  the stakes, adds a worse detail, narrows the mystery, or makes the tension
  physical. No flat exposition, no filler facts. The viewer should feel the
  walls closing in.
- POWERFUL PAYOFF: the reveal is the biggest moment of the video — ONE
  devastating line that names the answer in plain words, followed by the
  twist that makes it worse. Deliver it like a verdict, not a lecture.
- ENGAGEMENT TRICKS: the quiz pauses the video and demands a comment answer
  ("wrong answers only", "comment yours"); the twist opens an unresolved loop;
  the final line loops seamlessly back into the hook so the rewatch is invisible.

The six beats:
- hook    (0-3s): the single boldest visual + a verbal hook that states a
          shocking fact, bold claim, or curiosity gap — the CONTRADICTION, not
          the answer. NO questions like "have you ever wondered", NO "in this
          video", NO greetings. The hook VISUAL must instantly dramatize or
          CONTRADICT the title (title says a star "died in broad daylight" ->
          frame 0 is an ordinary bright blue daytime sky with an impossible
          star in it).
- setup   (3-10s): BUILD-UP — the minimum context that makes the mystery
          sharper, not softer. Tight, escalating.
- quiz    (10-15s): pause the viewer and weaponize them: "pause — can you spot
          it?" plus a comment-bait invitation ("wrong answers only in the
          comments"). The answer stays hidden.
- reveal  (15-25s): THE PAYOFF — one devastating line that finally names the
          answer with energy. This is the share moment.
- twist   (25-35s): the unexpected consequence / deeper fact that
          recontextualizes the payoff and keeps the loop unresolved.
- loop    (last 2-3s): a final line that flows seamlessly back into the hook line
          so the video loops. NEVER a CTA, never "like and subscribe", never
          "thanks for watching".

Voice lines must be SHORT (5-14 words each), concrete, and specific. No fluff
words. Numbers and specifics beat adjectives. Total word budget: {word_budget}
words for ~{duration}s at a natural narration pace.

For every voice line also give:
- imagePrompt: a visual scene description for an image generator (one clear
  subject, mood, lighting, composition — 15-30 words, no text-in-image
  requests). Always include the CAMERA treatment: framing (extreme close-up,
  wide establishing shot, low angle looking up) and a sense of movement or
  scale (approaching, towering above, plunging through, tiny against vast).
- camera: ONE of these exact tokens for the beat's camera move — "push-in",
  "pull-back", "orbit-left", "orbit-right", "drift-up", "drift-down",
  "pan-left", "pan-right", "crash-zoom", "settle". Calm beats get gentle moves
  (drift, settle); the reveal earns "crash-zoom" or a fast push-in.
- motion: true ONLY for 1-2 beats (ideally reveal/twist) where a real AI video
  clip (5s) would be dramatically better than a moving still — the explosion,
  the collision, the collapse. All other lines: false.
- nasaQuery: 2-3 words naming the real astronomical object / mission / telescope
  target for the NASA image archive (e.g. "neutron star", "black hole", "perseus
  cluster", "jwst deep field"). Use the most specific real object name possible;
  this is searched FIRST — AI images are only a fallback when NASA has nothing.
- sfxHint: one short sound-design cue suggestion (e.g. "soft whoosh",
  "deep impact", "riser", "tick", "sparkle")

Also give "hookCard": a 3-7 word ALL-CAPS banner burned over frame 0 that
punches the title's contradiction (e.g. "IT APPEARED AT NOON"). Wrap the 1-2
key words in _underscores_ — they render in the accent color.

Return ONLY valid JSON, exactly this shape:
{{
  "title": "punchy title under 60 chars",
  "hookCard": "THE _IMPOSSIBLE_ STAR",
  "vo": [
    {{"beat": "hook", "text": "...", "imagePrompt": "...", "camera": "push-in",
      "motion": false, "nasaQuery": "...", "sfxHint": "..."}}
  ],
  "beats": [
    {{"id": "hook", "visual": "one line describing the on-screen visual for this beat"}}
  ]
}}
Rules: 8-14 vo lines total. beats covers hook/setup/quiz/reveal/twist/loop in order.
The loop beat's visual must mirror the hook's visual."""


def generate_script(topic, style, duration, word_budget):
    prompt = f"TOPIC: {topic}\n"
    if style:
        prompt += f"STYLE / NICHE: {style}\n"
    prompt += SYSTEM_PROMPT.format(word_budget=word_budget, duration=duration)
    prompt += "\nReturn ONLY the JSON."

    for attempt in range(1, 4):
        try:
            raw = call_local_ai(prompt, temperature=0.75 + 0.1 * attempt)
            data = extract_json(raw)
            vo = data.get("vo")
            if (isinstance(vo, list) and len(vo) >= 6 and vo[0].get("text")
                    and all(v.get("text") for v in vo)):
                return data
            print(f"  attempt {attempt}: invalid structure, retrying…", file=sys.stderr)
        except (urllib.error.URLError, ValueError, RuntimeError, KeyError) as e:
            print(f"  attempt {attempt} failed: {e}", file=sys.stderr)
    sys.exit("local AI did not return a valid script after 3 attempts")


def normalize(data, out_dir, duration, fps=30):
    """Validate + add estimated timings (words-per-second pacing)."""
    vo = data["vo"]

    def sanitize_camera(v, i):
        cam = str(v.get("camera") or "").strip().lower()
        if cam not in CAMERA_MOVES:
            # deterministic fallback so adjacent beats never drift the same way
            cam = ["push-in", "orbit-right", "drift-up", "pan-left",
                   "orbit-left", "pull-back"][i % 6]
        v["camera"] = cam

    # motion clips are expensive: keep at most 2, prefer reveal/twist order
    motion_idx = [i for i, v in enumerate(vo) if v.get("motion")]
    keep = set(motion_idx[:2])
    for i, v in enumerate(vo):
        v["motion"] = i in keep

    words = [len(v["text"].split()) for v in vo]
    total_words = sum(words)
    # ~2.6 words/sec narration, plus a 0.35s gap between lines
    wps = 2.6
    gaps = 0.35 * (len(vo) - 1)
    speech = total_words / wps
    scale = 1.0
    total = gaps + speech
    if total > duration - 0.5:  # compress pacing to fit the requested duration
        scale = (duration - 0.5) / total
        total = duration - 0.5

    # WINNING FORMULA, structurally enforced in the timing:
    #   strong build-up  — pre-reveal lines run ~6% faster (tension accelerates)
    #   never reveal early — a beat of silence lands right BEFORE the reveal
    #   (anticipation), pushing the payoff late in the runtime
    #   powerful payoff  — the reveal line itself breathes (+12%) so it lands
    reveal_idx = next((i for i, v in enumerate(vo) if v.get("beat") == "reveal"), None)
    PRE_PACE = 0.94
    REVEAL_LAND = 1.12

    t = 0.25
    for i, (v, w) in enumerate(zip(vo, words)):
        sanitize_camera(v, i)
        d = max(1.0, (w / wps) * scale)
        if reveal_idx is not None:
            if i < reveal_idx:
                d *= PRE_PACE               # strong build-up: accelerating
            elif i == reveal_idx:
                d *= REVEAL_LAND            # powerful payoff: let it land
        v.setdefault("beat", "setup")
        v["start"] = round(t, 2)
        v["end"] = round(t + d, 2)
        gap = 0.35 * scale
        if reveal_idx is not None and i == reveal_idx - 1:
            gap = 0.75 * scale              # the silence before the drop
        t += d + gap

    beat_bounds = []
    beats = data.get("beats") or []
    for b in beats:
        b.setdefault("visual", "")
    # derive beat time ranges from the vo lines carrying that beat
    for v in vo:
        for b in beats:
            if b.get("id") == v.get("beat"):
                if not any(x["id"] == b["id"] for x in beat_bounds):
                    beat_bounds.append({"id": b["id"], "start": v["start"]})
                for x in beat_bounds:
                    if x["id"] == b["id"]:
                        x["end"] = round(v["end"] + 0.3, 2)
    if not beats:  # model omitted beats -> derive from vo beat tags
        seen = []
        for v in vo:
            if v["beat"] not in seen:
                seen.append(v["beat"])
        beats = [{"id": b, "start": 0.0, "end": 0.0,
                  "visual": next((v.get("imagePrompt", "") for v in vo if v["beat"] == b), "")}
                 for b in seen]
        beat_bounds = beats

    comp_id = "Auto" + slugify(data.get("title", out_dir), 24).replace("-", "").title()
    hook_card = str(data.get("hookCard") or data.get("title") or "WAIT FOR IT").strip()
    return {
        "id": os.path.basename(out_dir.rstrip("/")),
        "title": data.get("title", "Untitled Short"),
        "composition": comp_id[:30],
        "hookCard": hook_card,
        "format": {"width": 1080, "height": 1920, "fps": fps,
                   "durationSec": round(max(t + 0.75, 8.0), 2)},
        "vo": vo,
        "beats": beats,
        "voiceStatus": "pending:kokoro",
    }


def write_script_md(beats, topic, style, path):
    lines = [f"# {beats['title']}", "",
             f"- topic: {topic}",
             f"- style: {style or 'general'}",
             f"- duration: {beats['format']['durationSec']}s",
             f"- voice: local Kokoro TTS", "",
             "## Script", ""]
    for i, v in enumerate(beats["vo"]):
        lines.append(f"**[{v['beat'].upper()}] {v['start']:.1f}s** — {v['text']}  ")
        lines.append(f"  - *image:* {v.get('imagePrompt', '—')}  ")
        lines.append(f"  - *camera:* {v.get('camera', '—')}"
                     + ("  + AI video clip" if v.get("motion") else "") + "  ")
        lines.append(f"  - *sfx:* {v.get('sfxHint', '—')}  ")
    lines += ["", "## Beats", ""]
    for b in beats["beats"]:
        lines.append(f"- **{b['id']}** ({b.get('start', 0)}s–{b.get('end', 0)}s): {b.get('visual', '')}")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--topic", required=True)
    ap.add_argument("--out", required=True, help="project dir, e.g. shorts/auto-1-sky")
    ap.add_argument("--style", default=None, help='niche/style hint, e.g. "space documentary"')
    ap.add_argument("--duration", type=float, default=40.0)
    ap.add_argument("--word-budget", type=int, default=105)
    args = ap.parse_args()

    out_dir = os.path.abspath(args.out)
    os.makedirs(out_dir, exist_ok=True)

    print(f"generating script for: {args.topic!r}")
    if args.style:
        print(f"style: {args.style}")
    data = generate_script(args.topic, args.style, args.duration, args.word_budget)
    beats = normalize(data, out_dir, args.duration)

    beats_path = os.path.join(out_dir, "beats.json")
    with open(beats_path, "w", encoding="utf-8") as f:
        json.dump(beats, f, indent=2, ensure_ascii=False)
        f.write("\n")
    write_script_md(beats, args.topic, args.style, os.path.join(out_dir, "script.md"))

    print(f"title: {beats['title']}")
    print(f"  {len(beats['vo'])} vo lines, {beats['format']['durationSec']}s")
    print(f"  beats.json -> {os.path.relpath(beats_path, ROOT)}")
    print(f"  script.md  -> {os.path.relpath(os.path.join(out_dir, 'script.md'), ROOT)}")


if __name__ == "__main__":
    main()
