#!/usr/bin/env python3
"""
gen_script_long.py — LONG-FORM script (16:9, ~3-6 min) generated by the LOCAL AI.

Uses the same beats.json contract as the shorts (vo[] lines with beat tags and
timings from normalize_long) so the whole downstream factory — gen_voice word
timings, make_short's image strategies, the operator manifest — works
unchanged. Differences vs shorts:

  - format: 1920x1080 (landscape)
  - structure: cold-open HOOK -> 3-5 CHAPTERS (each a mini build-up/payoff
    arc) -> OUTRO with a natural CTA (long-form earns it)
  - chapter tags on vo lines: 'ch1'..'chN' (+ 'hook', 'outro') drive chapter
    title cards in the composition
  - per-line image strategy fields match the pipeline (nasaQuery for space,
    archiveQuery for history, bgPrompt for finance)
"""
import argparse
import json
import os
import re
import sys
import urllib.error

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "tools"))
from gen_script import call_local_ai, extract_json, slugify  # noqa: E402

CAMERA_MOVES = ["push-in", "pull-back", "orbit-left", "orbit-right", "drift-up",
                "drift-down", "pan-left", "pan-right", "crash-zoom", "settle"]

PIPELINE_FIELDS = {
    "space": 'nasaQuery (2-4 words: the real NASA archive target, e.g. "saturn rings")',
    "finance": 'bgPrompt (12-20 words: dark atmospheric US money/office/city scene, no text)',
    "history": 'archiveQuery (3-6 words: the real archival subject + year, e.g. "greenbrier bunker 1962")',
}

SYSTEM_PROMPT = """You are a documentary long-form writer for a faceless YouTube
channel (16:9 landscape, {duration}s ≈ {words} words at a natural narration pace).
Apply the winning formula at FULL SCALE:

- COLD OPEN (hook, first 2-3 lines): the most startling fact/image, stated as
  fact. Pose the central question — NEVER answer it here.
- CHAPTERS ({chapters} of them): each chapter is its own build-up -> mini-payoff
  arc that ALSO escalates the overall mystery. Chapter titles are 2-5 words,
  punchy, no spoiling.
- NEVER REVEAL EARLY: the central answer lands in the FINAL chapter's payoff.
  Earlier chapters deepen the mystery, raise stakes, and misdirect.
- PAYOFF: one devastating, plainly-worded revelation in the last chapter.
- OUTRO: 2-3 lines — resolve the loop, then a natural call to subscribe for the
  next investigation (long-form earns a CTA).

Rules:
- Voice lines: 8-18 words each, concrete and specific. US-English, US framing
  where natural (the audience is American).
- Return {lines} total vo lines across hook + chapters + outro.
- Every line gets: a 5-12 word visual description, one camera token
  ("push-in","pull-back","orbit-left","orbit-right","drift-up","drift-down",
  "pan-left","pan-right","crash-zoom","settle"), and {field}.

Return ONLY valid JSON exactly:
{{
  "title": "documentary title under 70 chars",
  "chapters": [{{"id": "ch1", "title": "THE FIRST CLUE"}}],
  "vo": [
    {{"beat": "hook", "text": "...", "visual": "...", "camera": "push-in",
      "{field_key}": "..."}}
  ]
}}
vo line "beat" values: "hook", then "{chapter_ids}", then "outro" — in that order."""


def generate_script(topic, style, duration, pipeline):
    chapters = 4 if duration >= 240 else 3
    lines = max(14, min(int(duration / 4.2), 40))
    words = int(duration * 2.5)
    chapter_ids = [f"ch{i+1}" for i in range(chapters)]
    field_key = {"space": "nasaQuery", "finance": "bgPrompt", "history": "archiveQuery"}.get(pipeline, "visual")
    prompt = f"""TOPIC: {topic}
STYLE / NICHE: {style or 'documentary'}
PIPELINE: {pipeline}
""" + SYSTEM_PROMPT.format(duration=int(duration), words=words, chapters=chapters,
                           lines=lines, field=PIPELINE_FIELDS.get(pipeline, 'visual (12-20 words)'),
                           field_key=field_key, chapter_ids=", ".join(chapter_ids)) + "\nReturn ONLY the JSON."

    for attempt in range(1, 4):
        try:
            raw = call_local_ai(prompt, max_tokens=3000, temperature=0.75 + 0.1 * attempt)
            data = extract_json(raw)
            vo = data.get("vo")
            if isinstance(vo, list) and len(vo) >= 10 and all(v.get("text") for v in vo):
                return data
            print(f"  attempt {attempt}: invalid structure, retrying…", file=sys.stderr)
        except (ValueError, RuntimeError, KeyError, urllib.error.URLError) as e:
            print(f"  attempt {attempt} failed: {e}", file=sys.stderr)
    sys.exit("local AI did not return a valid long-form script after 3 attempts")


def normalize_long(data, out_dir, duration, fps=30):
    """Timing (2.55 wps + gaps), camera sanitize, chapter index. Same
    beats.json contract as shorts -> the whole factory downstream works."""
    vo = data["vo"]
    chapter_titles = {c.get("id"): (c.get("title") or "").upper()
                      for c in (data.get("chapters") or [])}

    def sanitize_camera(v, i):
        cam = str(v.get("camera") or "").strip().lower()
        if cam not in CAMERA_MOVES:
            cam = ["push-in", "orbit-right", "drift-up", "pan-left",
                   "orbit-left", "pull-back"][i % 6]
        v["camera"] = cam

    words = [len(v["text"].split()) for v in vo]
    wps = 2.55
    t = 1.0
    reveal_idx = max(0, len(vo) - 3)  # the final chapter carries the payoff
    for i, (v, w) in enumerate(zip(vo, words)):
        sanitize_camera(v, i)
        d = max(2.0, (w / wps))
        if i < reveal_idx:
            d *= 0.97
        elif i == len(vo) - 3:
            d *= 1.08
        v.setdefault("beat", "ch1")
        v["start"] = round(t, 2)
        v["end"] = round(t + d, 2)
        t += d + 0.3
    total = round(t + 1.0, 2)

    comp_id = "Long" + slugify(data.get("title", out_dir), 24).replace("-", "").title()
    return {
        "id": os.path.basename(out_dir.rstrip("/")),
        "title": data.get("title", "Untitled Documentary"),
        "composition": comp_id[:30],
        "pipeline": data.get("pipeline"),
        "chapters": [{"id": c.get("id"), "title": (c.get("title") or "").upper(),
                      "start": next((v["start"] for v in vo if v.get("beat") == c.get("id")), 0)}
                     for c in (data.get("chapters") or [])],
        "format": {"width": 1920, "height": 1080, "fps": fps, "durationSec": total},
        "vo": vo,
        "voiceStatus": "pending:kokoro",
    }


def write_script_md(beats, topic, path):
    lines = [f"# {beats['title']}", "", f"- duration: {beats['format']['durationSec']}s (16:9)", ""]
    for c in beats.get("chapters", []):
        lines.append(f"## {c['title']}  ({c['start']}s)")
    lines.append("")
    for v in beats["vo"]:
        lines.append(f"**[{v['beat']}] {v['start']:.1f}s** — {v['text']}")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--topic", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--style", default=None)
    ap.add_argument("--pipeline", default="space", choices=["space", "finance", "history"])
    ap.add_argument("--duration", type=float, default=240.0)
    args = ap.parse_args()

    out_dir = os.path.abspath(args.out)
    os.makedirs(out_dir, exist_ok=True)
    print(f"generating LONG-FORM ({args.pipeline}) script for: {args.topic!r}")
    data = generate_script(args.topic, args.style, args.duration, args.pipeline)
    data["pipeline"] = args.pipeline
    beats = normalize_long(data, out_dir, args.duration)

    beats_path = os.path.join(out_dir, "beats.json")
    with open(beats_path, "w", encoding="utf-8") as f:
        json.dump(beats, f, indent=2, ensure_ascii=False)
        f.write("\n")
    write_script_md(beats, args.topic, os.path.join(out_dir, "script.md"))
    print(f"title: {beats['title']}  ({len(beats['vo'])} lines, {beats['format']['durationSec']}s, "
          f"{len(beats.get('chapters', []))} chapters)")


if __name__ == "__main__":
    main()
