#!/usr/bin/env python3
"""
make_long.py — LONG-FORM pipeline (16:9, 3-6 min documentary-style video).

  topic -> chaptered script (gen_script_long.py, local AI) -> per-line imagery
  (the channel's pipeline strategy: NASA / archives / AI plates) -> voice
  (Kokoro) -> 16:9 chaptered Remotion composition -> render -> mux -> FINAL.

Reuses the shorts factory's proven pieces (make_short.gen_images, gen_voice,
mix pattern) with a landscape edit format: chapter title cards, film-grade
imagery, quiet captions. Single output guarantee: shorts/<id>/output/<id>-final.mp4.

Usage:
  python tools/make_long.py --topic "..." --pipeline history --duration 240
  python tools/make_long.py --resume longs/long-1-greenbrier-bunker
"""
import argparse
import json
import os
import re
import shutil
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "tools"))

from gen_script import slugify  # noqa: E402
from gen_script_long import normalize_long  # noqa: E402

ACCENTS = ["#f5d76e", "#7dd3fc", "#a78bfa", "#fda4af", "#86efac"]


def sh(cmd, cwd=ROOT, check=True):
    print(f"  $ {' '.join(str(c) for c in cmd)}" if isinstance(cmd, list) else f"  $ {cmd}")
    r = subprocess.run(cmd if isinstance(cmd, list) else cmd, shell=isinstance(cmd, str),
                       cwd=cwd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    if r.stdout.strip():
        tail = "\n".join(r.stdout.strip().splitlines()[-10:])
        print("    " + tail.replace("\n", "\n    "))
    if check and r.returncode != 0:
        sys.exit(f"step failed ({r.returncode}): {cmd}\n{r.stdout[-2000:]}")
    return r


def next_index():
    n = 0
    base = os.path.join(ROOT, "longs")
    if os.path.isdir(base):
        for d in os.listdir(base):
            m = re.match(r"long-(\d+)", d)
            if m:
                n = max(n, int(m.group(1)))
    return n + 1


def gen_composition_long(beats, srcs, comp_id, shot_dir, accent):
    """16:9 chaptered composition: KenBurns imagery, chapter title cards on
    chapter starts, quiet captions, progress bar, cold-open title."""
    fps = beats["format"].get("fps", 30)
    total = beats["format"]["durationSec"]
    total_frames = round(total * fps)
    vo = beats["vo"]

    spans = []
    for i, v in enumerate(vo):
        start_f = 0 if i == 0 else max(0, round(float(v["start"]) * fps) - 2)
        end_f = (round(float(vo[i + 1]["start"]) * fps) - 2) if i + 1 < len(vo) else total_frames
        spans.append({"src": srcs[min(i, len(srcs) - 1)],
                      "start": start_f, "end": max(min(end_f, total_frames), start_f + 12),
                      "move": v.get("camera", "push-in"), "intensity": 0.85})

    beats_lit = "\n".join(
        f"  {{ src: '{s['src']}', start: {s['start']}, end: {s['end']}, "
        f"move: '{s['move']}', intensity: {s['intensity']} }}," for s in spans)

    # chapter title cards: first vo frame of each chapter, 3.5s hold
    cards = []
    for c in beats.get("chapters", []):
        start_f = round(float(c.get("start", 0)) * fps)
        cards.append({"title": c.get("title", ""), "from": start_f, "end": start_f + round(3.5 * fps)})
    cards_lit = "\n".join(
        f"  {{ title: {json.dumps(c['title'])}, from: {c['from']}, end: {c['end']} }}," for c in cards)
    cold_open = json.dumps(str(beats.get("title") or ""))

    tsx = f"""import React from 'react';
import {{ AbsoluteFill, Sequence, staticFile, useCurrentFrame }} from 'remotion';
import {{ Captions, ProgressBar }} from '../../lib/shorts';
import {{ KenBurnsImage }} from '../../lib/story';

// AUTO-GENERATED by tools/make_long.py — "{beats['title']}"
// 16:9 chaptered documentary: Ken Burns imagery, chapter cards, quiet captions.
export const compositionConfig = {{
  id: '{comp_id}',
  durationInSeconds: {round(total, 2)},
  fps: {fps},
  width: 1920,
  height: 1080,
}};

const ACCENT = '{accent}';
const TAIL = 14;

const BEATS = [
{beats_lit}
] as const;

const CHAPTERS = [
{cards_lit}
] as const;

const TITLE = {cold_open};

const ChapterCard: React.FC<{{ title: string; dur: number }}> = ({{ title, dur }}) => {{
  const f = useCurrentFrame();
  const p = Math.min(1, f / Math.max(1, dur));
  const fade = p < 0.2 ? p / 0.2 : (p > 0.8 ? (1 - p) / 0.2 : 1);
  return (
    <AbsoluteFill style={{ justifyContent: 'center', alignItems: 'center', opacity: Math.max(0, fade) }}>
      <AbsoluteFill style={{{{ background: 'rgba(6,8,12,0.72)' }}}} />
      <div style={{{{ textAlign: 'center' }}}}>
        <div style={{{{ width: 64, height: 4, background: ACCENT, margin: '0 auto 26px' }}}} />
        <div style={{{{ fontFamily: 'Inter, sans-serif', fontWeight: 900, fontSize: 76,
                        letterSpacing: 3, color: '#f4f2ee', textTransform: 'uppercase' }}}}>{title}</div>
      </div>
    </AbsoluteFill>
  );
}};

const {comp_id}: React.FC = () => {{
  return (
    <AbsoluteFill style={{{{ background: '#0b0d12' }}}}>
      {{BEATS.map((b, i) => {{
        const isLast = i === BEATS.length - 1;
        const dur = b.end - b.start + (isLast ? 0 : TAIL);
        return (
          <Sequence key={{i}} from={{b.start}} durationInFrames={{dur}}>
            <KenBurnsImage src={{b.src}} dur={{dur}} move={{b.move}} intensity={{b.intensity}}
              fadeIn={{i === 0 ? 0 : 12}} />
          </Sequence>
        );
      }})}}
      <Sequence from={{0}} durationInFrames={{150}}>
        <AbsoluteFill style={{{{ justifyContent: 'center', alignItems: 'center', background: 'rgba(6,8,12,0.6)' }}}}>
          <div style={{{{ textAlign: 'center', padding: '0 120px' }}}}>
            <div style={{{{ fontFamily: 'Inter, sans-serif', fontWeight: 800, fontSize: 26,
                            letterSpacing: 6, color: ACCENT, textTransform: 'uppercase', marginBottom: 20 }}}}>Documentary</div>
            <div style={{{{ fontFamily: 'Inter, sans-serif', fontWeight: 900, fontSize: 88,
                            letterSpacing: 1, color: '#f4f2ee', lineHeight: 1.1 }}}}>{TITLE}</div>
          </div>
        </AbsoluteFill>
      </Sequence>
      {{CHAPTERS.map((c, i) => (
        <Sequence key={{'c' + i}} from={{c.from}} durationInFrames={{c.end - c.from}}>
          <ChapterCard title={{c.title}} dur={{c.end - c.from}} />
        </Sequence>
      ))}}
      <Captions lines={{VO}} y={{930}} size={{38}} accent={{ACCENT}} maxWords={{7}} plate />
      <ProgressBar color={{ACCENT}} />
    </AbsoluteFill>
  );
}};

export default {comp_id};
"""
    path = os.path.join(shot_dir, f"{comp_id}.tsx")
    with open(path, "w", encoding="utf-8") as f:
        f.write(tsx)
    print(f"    composition -> {os.path.relpath(path, ROOT)}")
    return path


def main():
    ap = argparse.ArgumentParser(description="Long-form (16:9) documentary factory")
    ap.add_argument("--topic")
    ap.add_argument("--resume")
    ap.add_argument("--pipeline", default="space", choices=["space", "finance", "history"])
    ap.add_argument("--style", default=None)
    ap.add_argument("--voice", default="dynamic")
    ap.add_argument("--duration", type=float, default=240.0)
    ap.add_argument("--keep-intermediates", action="store_true")
    args = ap.parse_args()

    if not args.topic and not args.resume:
        sys.exit("need --topic or --resume longs/<id>")

    if args.resume:
        proj_dir = os.path.abspath(args.resume)
        proj_id = os.path.basename(proj_dir.rstrip("/"))
    else:
        proj_id = f"long-{next_index()}-{slugify(args.topic, 36)}"
        proj_dir = os.path.join(ROOT, "longs", proj_id)
        os.makedirs(proj_dir, exist_ok=True)

    beats_path = os.path.join(proj_dir, "beats.json")
    media_dir = os.path.join(ROOT, "media", "projects", proj_id)

    # 1. script
    if not os.path.exists(beats_path):
        print(f"\n[1/6] long-form script for: {args.topic!r}")
        sh([sys.executable, "tools/gen_script_long.py", "--topic", args.topic,
            "--out", proj_dir, "--pipeline", args.pipeline,
            "--duration", str(args.duration)]
           + (["--style", args.style] if args.style else []))
    beats = json.load(open(beats_path, encoding="utf-8"))
    pipeline = beats.get("pipeline", args.pipeline)
    comp_id = beats.get("composition")
    total = float(beats["format"]["durationSec"])
    print(f"      '{beats['title']}'  ({len(beats['vo'])} lines, {total:.0f}s, {len(beats.get('chapters', []))} chapters)")

    # 2. imagery — reuse the shorts factory's pipeline strategy
    print(f"\n[2/6] chapter imagery ({pipeline})")
    os.makedirs(media_dir, exist_ok=True)
    import make_short
    srcs = make_short.gen_images(pipeline, beats, proj_dir, media_dir, "1K")

    # 3. voice
    shot_dir = os.path.join(ROOT, "remotion", "src", "shots", comp_id.lower())
    print("\n[3/6] voice (local Kokoro TTS)")
    sh([sys.executable, "tools/gen_voice.py", "--beats", beats_path,
        "--voice", args.voice, "--emit-ts", os.path.join(shot_dir, "vo.gen.ts")])
    beats = json.load(open(beats_path, encoding="utf-8"))
    total = float(beats["format"]["durationSec"])

    # 4. composition + render
    accent = ACCENTS[(next_index() - 1) % len(ACCENTS)]
    print(f"\n[4/6] composition + render (accent {accent})")
    gen_composition_long(beats, srcs, comp_id, shot_dir, accent)
    sh(["npm", "run", "gen"], cwd=os.path.join(ROOT, "remotion"))
    sh(["node", "scripts/render-all.mjs", comp_id, "--scale=1"], cwd=os.path.join(ROOT, "remotion"))
    rendered = os.path.join(ROOT, "remotion", "out", f"{comp_id}.mp4")
    if not os.path.exists(rendered):
        sys.exit(f"render did not produce {rendered}")

    # 5. mux voice
    print("\n[5/6] voice mux")
    voiced = os.path.join(ROOT, "remotion", "out", f"{comp_id}-voiced.mp4")
    sh(["ffmpeg", "-y", "-v", "error", "-i", rendered, "-i", os.path.join(proj_dir, "voice", "voice.wav"),
        "-map", "0:v", "-map", "1:a", "-c:v", "copy", "-c:a", "aac", "-b:a", "192k", "-t", str(total), voiced])

    # 6. final only
    print("\n[6/6] final")
    out_dir = os.path.join(proj_dir, "output")
    os.makedirs(out_dir, exist_ok=True)
    final_copy = os.path.join(out_dir, f"{proj_id}-final.mp4")
    shutil.copy2(voiced, final_copy)
    if not args.keep_intermediates:
        for p in (rendered, voiced):
            if os.path.exists(p):
                os.remove(p)

    qc = None
    try:
        sh([sys.executable, "tools/qc_check.py", "--short-dir", proj_dir], check=False)
        qc_path = os.path.join(proj_dir, "qc-report.json")
        qc = json.load(open(qc_path, encoding="utf-8")) if os.path.exists(qc_path) else None
    except Exception:
        pass

    print("\n" + "=" * 60)
    print(f"DONE  {beats['title']}")
    print(f"      {final_copy}")
    print(f"      {total:.0f}s  format=long  qc={qc['verdict'] if qc else 'skipped'}")
    print("=" * 60)
    print("FINAL:" + json.dumps({
        "proj_id": proj_id, "title": beats["title"], "final": final_copy,
        "beats": beats_path, "duration": round(total, 2), "composition": comp_id,
        "voice": beats.get("voiceStatus"), "pipeline": pipeline, "format": "long",
        "images": len(srcs), "accent": accent,
        "qc": ({"verdict": qc.get("verdict")} if qc else None),
    }, ensure_ascii=False))


if __name__ == "__main__":
    main()
