import React from 'react';
import { AbsoluteFill, OffthreadVideo, Sequence, staticFile } from 'remotion';
import { Captions, ProgressBar } from '../../lib/shorts';
import { KenBurnsImage, StoryVignette } from '../../lib/story';
import { VO } from './vo.gen';

// =============================================================================
// AUTO-GENERATED by tools/make_short.py — "The Dead Star Spinning 716 Times Per Second"
// Camera moves + intensity follow the beat grammar (calm -> building -> payoff).
// motion:true beats use real AI video when FAL is configured, Ken Burns otherwise.
// =============================================================================
export const compositionConfig = {
  id: 'AutoThedeadstarspinning7',
  durationInSeconds: 39.57,
  fps: 30,
  width: 1080,
  height: 1920,
};

const ACCENT = '#a78bfa';
const TAIL = 20; // frames each beat under-laps the next so the crossfade never gaps

const BEATS = [
  { src: 'projects/auto-27-the-dead-star-spinning-716-times/b00-hook.jpg', start: 0, end: 177, move: 'push-in', intensity: 0.5, clip: null, fadeIn: 0 },
  { src: 'projects/auto-27-the-dead-star-spinning-716-times/b01-setup.nasa.jpg', start: 177, end: 326, move: 'orbit-left', intensity: 0.66, clip: null, fadeIn: 14 },
  { src: 'projects/auto-27-the-dead-star-spinning-716-times/b02-setup.nasa.jpg', start: 326, end: 487, move: 'crash-zoom', intensity: 0.71, clip: null, fadeIn: 14 },
  { src: 'projects/auto-27-the-dead-star-spinning-716-times/b03-quiz.jpg', start: 487, end: 648, move: 'settle', intensity: 0.75, clip: null, fadeIn: 14 },
  { src: 'projects/auto-27-the-dead-star-spinning-716-times/b04-reveal.jpg', start: 648, end: 797, move: 'push-in', intensity: 1.2, clip: null, fadeIn: 14 },
  { src: 'projects/auto-27-the-dead-star-spinning-716-times/b05-twist.nasa.jpg', start: 797, end: 934, move: 'orbit-right', intensity: 1.15, clip: null, fadeIn: 14 },
  { src: 'projects/auto-27-the-dead-star-spinning-716-times/b06-twist.nasa.jpg', start: 934, end: 1060, move: 'pull-back', intensity: 1.15, clip: null, fadeIn: 14 },
  { src: 'projects/auto-27-the-dead-star-spinning-716-times/b07-loop.nasa.jpg', start: 1060, end: 1187, move: 'push-in', intensity: 0.7, clip: null, fadeIn: 14 },
] as const;

const AutoThedeadstarspinning7: React.FC = () => {
  return (
    <AbsoluteFill style={{ background: '#0b0d12' }}>
      {BEATS.map((b, i) => {
        const isLast = i === BEATS.length - 1;
        const dur = b.end - b.start + (isLast ? 0 : TAIL);
        return (
          <Sequence key={i} from={b.start} durationInFrames={dur}>
            {b.clip ? (
              <OffthreadVideo src={staticFile(b.clip)} muted
                style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
            ) : (
              <KenBurnsImage src={b.src} dur={dur} move={b.move}
                intensity={b.intensity} fadeIn={b.fadeIn} />
            )}
          </Sequence>
        );
      })}
      <StoryVignette strength={0.34} />
      <Captions lines={VO} y={1330} size={54} accent={ACCENT} maxWords={5} plate />
      <ProgressBar color={ACCENT} />
    </AbsoluteFill>
  );
};

export default AutoThedeadstarspinning7;
