import React from 'react';
import { AbsoluteFill, Sequence } from 'remotion';
import { Captions, ProgressBar } from '../../lib/shorts';
import { KenBurnsImage, StoryVignette } from '../../lib/story';
import { VO } from './vo.gen';

// =============================================================================
// AUTO-GENERATED by tools/make_short.py — "The Star That Died in Broad Daylight"
// Ken Burns beat images + word-pop captions + progress bar. Local pipeline:
// local-AI script -> Pollinations images -> Kokoro voice -> this render.
// =============================================================================
export const compositionConfig = {
  id: 'AutoThestarthatdiedinbr',
  durationInSeconds: 37.26,
  fps: 30,
  width: 1080,
  height: 1920,
};

const ACCENT = '#f5d76e';
const TAIL = 20; // frames each beat under-laps the next so the crossfade never gaps

const BEATS = [
  { src: 'projects/auto-5-the-crab-nebula-explosion-seen-i/b00-hook.nasa.jpg', start: 6, end: 155, variant: 0, fadeIn: 0 },
  { src: 'projects/auto-5-the-crab-nebula-explosion-seen-i/b01-hook.nasa.jpg', start: 155, end: 303, variant: 1, fadeIn: 14 },
  { src: 'projects/auto-5-the-crab-nebula-explosion-seen-i/b02-setup.nasa.jpg', start: 303, end: 464, variant: 2, fadeIn: 14 },
  { src: 'projects/auto-5-the-crab-nebula-explosion-seen-i/b03-quiz.nasa.jpg', start: 464, end: 613, variant: 3, fadeIn: 14 },
  { src: 'projects/auto-5-the-crab-nebula-explosion-seen-i/b04-reveal.nasa.jpg', start: 613, end: 750, variant: 4, fadeIn: 14 },
  { src: 'projects/auto-5-the-crab-nebula-explosion-seen-i/b05-reveal.nasa.jpg', start: 750, end: 876, variant: 5, fadeIn: 14 },
  { src: 'projects/auto-5-the-crab-nebula-explosion-seen-i/b06-twist.nasa.jpg', start: 876, end: 1025, variant: 0, fadeIn: 14 },
  { src: 'projects/auto-5-the-crab-nebula-explosion-seen-i/b07-loop.nasa.jpg', start: 1025, end: 1118, variant: 1, fadeIn: 14 },
] as const;

const AutoThestarthatdiedinbr: React.FC = () => {
  return (
    <AbsoluteFill style={{ background: '#0b0d12' }}>
      {BEATS.map((b, i) => {
        const isLast = i === BEATS.length - 1;
        const dur = b.end - b.start + (isLast ? 0 : TAIL);
        return (
          <Sequence key={i} from={b.start} durationInFrames={dur}>
            <KenBurnsImage src={b.src} dur={dur} variant={b.variant} fadeIn={b.fadeIn} />
          </Sequence>
        );
      })}
      <StoryVignette strength={0.34} />
      <Captions lines={VO} y={1330} size={54} accent={ACCENT} maxWords={4} plate />
      <ProgressBar color={ACCENT} />
    </AbsoluteFill>
  );
};

export default AutoThestarthatdiedinbr;
