import React from 'react';
import { AbsoluteFill, OffthreadVideo, Sequence, staticFile } from 'remotion';
import { Captions, ProgressBar } from '../../lib/shorts';
import { KenBurnsImage, StoryVignette } from '../../lib/story';
import { VO } from './vo.gen';

// =============================================================================
// AUTO-GENERATED by tools/make_short.py — "The Star That Died in Broad Daylight"
// Camera moves + intensity follow the beat grammar (calm -> building -> payoff).
// motion:true beats use real AI video when FAL is configured, Ken Burns otherwise.
// =============================================================================
export const compositionConfig = {
  id: 'AutoThestarthatdiedinbr',
  durationInSeconds: 34.18,
  fps: 30,
  width: 1080,
  height: 1920,
};

const ACCENT = '#a78bfa';
const TAIL = 20; // frames each beat under-laps the next so the crossfade never gaps

const BEATS = [
  { src: 'projects/auto-7-the-star-that-died-in-broad-dayl/b00-hook.nasa.jpg', start: 0, end: 143, move: 'push-in', intensity: 0.5, clip: null, fadeIn: 0 },
  { src: 'projects/auto-7-the-star-that-died-in-broad-dayl/b01-setup.nasa.jpg', start: 143, end: 280, move: 'drift-up', intensity: 0.66, clip: null, fadeIn: 14 },
  { src: 'projects/auto-7-the-star-that-died-in-broad-dayl/b02-setup.nasa.jpg', start: 280, end: 418, move: 'pull-back', intensity: 0.71, clip: null, fadeIn: 14 },
  { src: 'projects/auto-7-the-star-that-died-in-broad-dayl/b03-quiz.nasa.jpg', start: 418, end: 555, move: 'settle', intensity: 0.75, clip: null, fadeIn: 14 },
  { src: 'projects/auto-7-the-star-that-died-in-broad-dayl/b04-reveal.nasa.jpg', start: 555, end: 658, move: 'crash-zoom', intensity: 1.2, clip: null, fadeIn: 14 },
  { src: 'projects/auto-7-the-star-that-died-in-broad-dayl/b05-twist.nasa.jpg', start: 658, end: 807, move: 'orbit-left', intensity: 1.15, clip: null, fadeIn: 14 },
  { src: 'projects/auto-7-the-star-that-died-in-broad-dayl/b06-twist.nasa.jpg', start: 807, end: 933, move: 'orbit-right', intensity: 1.15, clip: null, fadeIn: 14 },
  { src: 'projects/auto-7-the-star-that-died-in-broad-dayl/b07-loop.nasa.jpg', start: 933, end: 1025, move: 'push-in', intensity: 0.7, clip: null, fadeIn: 14 },
] as const;

const AutoThestarthatdiedinbr: React.FC = () => {
  return (
    <AbsoluteFill style={{ background: '#0b0d12' }}>
      {BEATS.map((b, i) => {
        const isLast = i === BEATS.length - 1;
        const dur = b.end - b.start + (isLast ? 0 : TAIL);
        return (
          <Sequence key={i} from={b.start} durationInFrames={dur}>
            {b.clip ? (
              <OffthreadVideo src={staticFile(b.clip)} muted
                style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
            ) : (
              <KenBurnsImage src={b.src} dur={dur} move={b.move}
                intensity={b.intensity} fadeIn={b.fadeIn} />
            )}
          </Sequence>
        );
      })}
      <StoryVignette strength={0.34} />
      <Captions lines={VO} y={1330} size={54} accent={ACCENT} maxWords={5} plate />
      <ProgressBar color={ACCENT} />
    </AbsoluteFill>
  );
};

export default AutoThestarthatdiedinbr;
