import React from 'react';
import { AbsoluteFill, Sequence } from 'remotion';
import { Captions, ProgressBar } from '../../lib/shorts';
import { KenBurnsImage, StoryVignette } from '../../lib/story';
import { VO } from './vo.gen';

// =============================================================================
// AUTO-GENERATED by tools/make_short.py — "The Terrifying Sound of a Black Hole"
// Ken Burns beat images + word-pop captions + progress bar. Local pipeline:
// local-AI script -> Pollinations images -> Kokoro voice -> this render.
// =============================================================================
export const compositionConfig = {
  id: 'AutoTheterrifyingsoundof',
  durationInSeconds: 38.0,
  fps: 30,
  width: 1080,
  height: 1920,
};

const ACCENT = '#7dd3fc';
const TAIL = 20; // frames each beat under-laps the next so the crossfade never gaps

const BEATS = [
  { src: 'projects/auto-1-the-sound-a-black-hole-makes/b00-hook.jpg', start: 6, end: 132, variant: 0, fadeIn: 0 },
  { src: 'projects/auto-1-the-sound-a-black-hole-makes/b01-setup.jpg', start: 132, end: 257, variant: 1, fadeIn: 14 },
  { src: 'projects/auto-1-the-sound-a-black-hole-makes/b02-setup.jpg', start: 257, end: 383, variant: 2, fadeIn: 14 },
  { src: 'projects/auto-1-the-sound-a-black-hole-makes/b03-quiz.jpg', start: 383, end: 509, variant: 3, fadeIn: 14 },
  { src: 'projects/auto-1-the-sound-a-black-hole-makes/b04-reveal.jpg', start: 509, end: 658, variant: 4, fadeIn: 14 },
  { src: 'projects/auto-1-the-sound-a-black-hole-makes/b05-reveal.jpg', start: 658, end: 772, variant: 5, fadeIn: 14 },
  { src: 'projects/auto-1-the-sound-a-black-hole-makes/b06-twist.jpg', start: 772, end: 910, variant: 0, fadeIn: 14 },
  { src: 'projects/auto-1-the-sound-a-black-hole-makes/b07-twist.jpg', start: 910, end: 1059, variant: 1, fadeIn: 14 },
  { src: 'projects/auto-1-the-sound-a-black-hole-makes/b08-loop.jpg', start: 1059, end: 1140, variant: 2, fadeIn: 14 },
] as const;

const AutoTheterrifyingsoundof: React.FC = () => {
  return (
    <AbsoluteFill style={{ background: '#0b0d12' }}>
      {BEATS.map((b, i) => {
        const isLast = i === BEATS.length - 1;
        const dur = b.end - b.start + (isLast ? 0 : TAIL);
        return (
          <Sequence key={i} from={b.start} durationInFrames={dur}>
            <KenBurnsImage src={b.src} dur={dur} variant={b.variant} fadeIn={b.fadeIn} />
          </Sequence>
        );
      })}
      <StoryVignette strength={0.34} />
      <Captions lines={VO} y={1330} size={54} accent={ACCENT} maxWords={4} plate />
      <ProgressBar color={ACCENT} />
    </AbsoluteFill>
  );
};

export default AutoTheterrifyingsoundof;
