import React from 'react';
import { AbsoluteFill, OffthreadVideo, Sequence, staticFile } from 'remotion';
import { Captions, ProgressBar } from '../../lib/shorts';
import { KenBurnsImage, StoryVignette } from '../../lib/story';
import { VO } from './vo.gen';

// =============================================================================
// AUTO-GENERATED by tools/make_short.py — "The Deepest Sound in the Universe"
// Camera moves + intensity follow the beat grammar (calm -> building -> payoff).
// motion:true beats use real AI video when FAL is configured, Ken Burns otherwise.
// =============================================================================
export const compositionConfig = {
  id: 'AutoThedeepestsoundinthe',
  durationInSeconds: 40.3,
  fps: 30,
  width: 1080,
  height: 1920,
};

const ACCENT = '#7dd3fc';
const TAIL = 20; // frames each beat under-laps the next so the crossfade never gaps

const BEATS = [
  { src: 'projects/auto-11-the-sound-of-a-black-hole-record/b00-hook.nasa.jpg', start: 0, end: 120, move: 'push-in', intensity: 0.5, clip: null, fadeIn: 0 },
  { src: 'projects/auto-11-the-sound-of-a-black-hole-record/b01-hook.nasa.jpg', start: 120, end: 246, move: 'crash-zoom', intensity: 0.5, clip: null, fadeIn: 14 },
  { src: 'projects/auto-11-the-sound-of-a-black-hole-record/b02-setup.nasa.jpg', start: 246, end: 372, move: 'orbit-left', intensity: 0.7, clip: null, fadeIn: 14 },
  { src: 'projects/auto-11-the-sound-of-a-black-hole-record/b03-setup.nasa.jpg', start: 372, end: 497, move: 'drift-up', intensity: 0.75, clip: null, fadeIn: 14 },
  { src: 'projects/auto-11-the-sound-of-a-black-hole-record/b04-quiz.nasa.jpg', start: 497, end: 647, move: 'push-in', intensity: 0.75, clip: null, fadeIn: 14 },
  { src: 'projects/auto-11-the-sound-of-a-black-hole-record/b05-reveal.jpg', start: 647, end: 784, move: 'push-in', intensity: 1.2, clip: null, fadeIn: 14 },
  { src: 'projects/auto-11-the-sound-of-a-black-hole-record/b06-reveal.nasa.jpg', start: 784, end: 921, move: 'orbit-right', intensity: 1.2, clip: null, fadeIn: 14 },
  { src: 'projects/auto-11-the-sound-of-a-black-hole-record/b07-twist.nasa.jpg', start: 921, end: 1070, move: 'pull-back', intensity: 1.15, clip: null, fadeIn: 14 },
  { src: 'projects/auto-11-the-sound-of-a-black-hole-record/b08-loop.jpg', start: 1070, end: 1209, move: 'settle', intensity: 0.7, clip: null, fadeIn: 14 },
] as const;

const AutoThedeepestsoundinthe: React.FC = () => {
  return (
    <AbsoluteFill style={{ background: '#0b0d12' }}>
      {BEATS.map((b, i) => {
        const isLast = i === BEATS.length - 1;
        const dur = b.end - b.start + (isLast ? 0 : TAIL);
        return (
          <Sequence key={i} from={b.start} durationInFrames={dur}>
            {b.clip ? (
              <OffthreadVideo src={staticFile(b.clip)} muted
                style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
            ) : (
              <KenBurnsImage src={b.src} dur={dur} move={b.move}
                intensity={b.intensity} fadeIn={b.fadeIn} />
            )}
          </Sequence>
        );
      })}
      <StoryVignette strength={0.34} />
      <Captions lines={VO} y={1330} size={54} accent={ACCENT} maxWords={5} plate />
      <ProgressBar color={ACCENT} />
    </AbsoluteFill>
  );
};

export default AutoThedeepestsoundinthe;
