import React from 'react';
import { AbsoluteFill, Sequence } from 'remotion';
import { Captions, ProgressBar } from '../../lib/shorts';
import { KenBurnsImage, StoryVignette } from '../../lib/story';
import { VO } from './vo.gen';

// =============================================================================
// AUTO-GENERATED by tools/make_short.py — "The Cosmic Jet That Swallows Galaxies"
// Ken Burns beat images + word-pop captions + progress bar. Local pipeline:
// local-AI script -> Pollinations images -> Kokoro voice -> this render.
// =============================================================================
export const compositionConfig = {
  id: 'AutoThecosmicjetthatswal',
  durationInSeconds: 40.82,
  fps: 30,
  width: 1080,
  height: 1920,
};

const ACCENT = '#86efac';
const TAIL = 20; // frames each beat under-laps the next so the crossfade never gaps

const BEATS = [
  { src: 'projects/auto-4-the-hercules-a-galaxy-jet-that-i/b00-hook.nasa.jpg', start: 6, end: 152, variant: 0, fadeIn: 0 },
  { src: 'projects/auto-4-the-hercules-a-galaxy-jet-that-i/b01-hook.nasa.jpg', start: 152, end: 289, variant: 1, fadeIn: 14 },
  { src: 'projects/auto-4-the-hercules-a-galaxy-jet-that-i/b02-setup.nasa.jpg', start: 289, end: 425, variant: 2, fadeIn: 14 },
  { src: 'projects/auto-4-the-hercules-a-galaxy-jet-that-i/b03-setup.nasa.jpg', start: 425, end: 540, variant: 3, fadeIn: 14 },
  { src: 'projects/auto-4-the-hercules-a-galaxy-jet-that-i/b04-quiz.nasa.jpg', start: 540, end: 677, variant: 4, fadeIn: 14 },
  { src: 'projects/auto-4-the-hercules-a-galaxy-jet-that-i/b05-reveal.nasa.jpg', start: 677, end: 792, variant: 5, fadeIn: 14 },
  { src: 'projects/auto-4-the-hercules-a-galaxy-jet-that-i/b06-reveal.nasa.jpg', start: 792, end: 907, variant: 0, fadeIn: 14 },
  { src: 'projects/auto-4-the-hercules-a-galaxy-jet-that-i/b07-twist.nasa.jpg', start: 907, end: 1044, variant: 1, fadeIn: 14 },
  { src: 'projects/auto-4-the-hercules-a-galaxy-jet-that-i/b08-twist.nasa.jpg', start: 1044, end: 1148, variant: 2, fadeIn: 14 },
  { src: 'projects/auto-4-the-hercules-a-galaxy-jet-that-i/b09-loop.nasa.jpg', start: 1148, end: 1225, variant: 3, fadeIn: 14 },
] as const;

const AutoThecosmicjetthatswal: React.FC = () => {
  return (
    <AbsoluteFill style={{ background: '#0b0d12' }}>
      {BEATS.map((b, i) => {
        const isLast = i === BEATS.length - 1;
        const dur = b.end - b.start + (isLast ? 0 : TAIL);
        return (
          <Sequence key={i} from={b.start} durationInFrames={dur}>
            <KenBurnsImage src={b.src} dur={dur} variant={b.variant} fadeIn={b.fadeIn} />
          </Sequence>
        );
      })}
      <StoryVignette strength={0.34} />
      <Captions lines={VO} y={1330} size={54} accent={ACCENT} maxWords={4} plate />
      <ProgressBar color={ACCENT} />
    </AbsoluteFill>
  );
};

export default AutoThecosmicjetthatswal;
