import React from 'react';
import { AbsoluteFill, Sequence, staticFile, useCurrentFrame } from 'remotion';
import { Captions, ProgressBar } from '../../lib/shorts';
import { KenBurnsImage } from '../../lib/story';
import { VO } from './vo.gen';

// AUTO-GENERATED by tools/make_long.py — "The Silent 401k Trap Draining Your Retirement"
// 16:9 chaptered documentary: Ken Burns imagery, chapter cards, quiet captions.
export const compositionConfig = {
  id: 'LongThesilent401Ktrapdra',
  durationInSeconds: 120.97,
  fps: 30,
  width: 1920,
  height: 1080,
};

const ACCENT = '#7dd3fc';
const TAIL = 14;

const BEATS = [
  { src: 'projects/long-1-the-401k-fee-trap-quietly-draining-a/b00-hook.jpg', start: 0, end: 220, move: 'push-in', intensity: 0.85 },
  { src: 'projects/long-1-the-401k-fee-trap-quietly-draining-a/b01-hook.jpg', start: 220, end: 400, move: 'drift-down', intensity: 0.85 },
  { src: 'projects/long-1-the-401k-fee-trap-quietly-draining-a/b02-hook.jpg', start: 400, end: 580, move: 'orbit-left', intensity: 0.85 },
  { src: 'projects/long-1-the-401k-fee-trap-quietly-draining-a/b03-ch1.jpg', start: 580, end: 771, move: 'pan-right', intensity: 0.85 },
  { src: 'projects/long-1-the-401k-fee-trap-quietly-draining-a/b04-ch1.jpg', start: 771, end: 963, move: 'pull-back', intensity: 0.85 },
  { src: 'projects/long-1-the-401k-fee-trap-quietly-draining-a/b05-ch1.jpg', start: 963, end: 1155, move: 'push-in', intensity: 0.85 },
  { src: 'projects/long-1-the-401k-fee-trap-quietly-draining-a/b06-ch1.jpg', start: 1155, end: 1335, move: 'drift-up', intensity: 0.85 },
  { src: 'projects/long-1-the-401k-fee-trap-quietly-draining-a/b07-ch2.jpg', start: 1335, end: 1515, move: 'orbit-right', intensity: 0.85 },
  { src: 'projects/long-1-the-401k-fee-trap-quietly-draining-a/b08-ch2.jpg', start: 1515, end: 1695, move: 'settle', intensity: 0.85 },
  { src: 'projects/long-1-the-401k-fee-trap-quietly-draining-a/b09-ch2.jpg', start: 1695, end: 1875, move: 'pan-left', intensity: 0.85 },
  { src: 'projects/long-1-the-401k-fee-trap-quietly-draining-a/b10-ch2.jpg', start: 1875, end: 2067, move: 'push-in', intensity: 0.85 },
  { src: 'projects/long-1-the-401k-fee-trap-quietly-draining-a/b11-ch3.jpg', start: 2067, end: 2236, move: 'crash-zoom', intensity: 0.85 },
  { src: 'projects/long-1-the-401k-fee-trap-quietly-draining-a/b12-ch3.jpg', start: 2236, end: 2427, move: 'drift-down', intensity: 0.85 },
  { src: 'projects/long-1-the-401k-fee-trap-quietly-draining-a/b13-ch3.jpg', start: 2427, end: 2619, move: 'pull-back', intensity: 0.85 },
  { src: 'projects/long-1-the-401k-fee-trap-quietly-draining-a/b14-ch3.jpg', start: 2619, end: 2810, move: 'orbit-left', intensity: 0.85 },
  { src: 'projects/long-1-the-401k-fee-trap-quietly-draining-a/b15-ch3.jpg', start: 2810, end: 3002, move: 'settle', intensity: 0.85 },
  { src: 'projects/long-1-the-401k-fee-trap-quietly-draining-a/b16-outro.jpg', start: 3002, end: 3214, move: 'pull-back', intensity: 0.85 },
  { src: 'projects/long-1-the-401k-fee-trap-quietly-draining-a/b17-outro.jpg', start: 3214, end: 3412, move: 'push-in', intensity: 0.85 },
  { src: 'projects/long-1-the-401k-fee-trap-quietly-draining-a/b18-outro.jpg', start: 3412, end: 3629, move: 'drift-up', intensity: 0.85 },
] as const;

const CHAPTERS = [
  { title: "THE INVISIBLE DEDUCTION", from: 582, end: 687 },
  { title: "THE COMPOUNDING ILLUSION", from: 1337, end: 1442 },
  { title: "THE RETAINER FEE", from: 2069, end: 2174 },
] as const;

const TITLE = "The Silent 401k Trap Draining Your Retirement";

const ChapterCard: React.FC<{ title: string; dur: number }> = ({ title, dur }) => {
  const f = useCurrentFrame();
  const p = Math.min(1, f / Math.max(1, dur));
  const fade = p < 0.2 ? p / 0.2 : (p > 0.8 ? (1 - p) / 0.2 : 1);
  return (
    <AbsoluteFill style={{ justifyContent: 'center', alignItems: 'center', opacity: Math.max(0, fade) }}>
      <AbsoluteFill style={{ background: 'rgba(6,8,12,0.72)' }} />
      <div style={{ textAlign: 'center' }}>
        <div style={{ width: 64, height: 4, background: ACCENT, margin: '0 auto 26px' }} />
        <div style={{ fontFamily: 'Inter, sans-serif', fontWeight: 900, fontSize: 76,
                        letterSpacing: 3, color: '#f4f2ee', textTransform:'uppercase'}}>{title}</div>
      </div>
    </AbsoluteFill>
  );
};

const LongThesilent401Ktrapdra: React.FC = () => {
  return (
    <AbsoluteFill style={{ background: '#0b0d12' }}>
      {BEATS.map((b, i) => {
        const isLast = i === BEATS.length - 1;
        const dur = b.end - b.start + (isLast ? 0 : TAIL);
        return (
          <Sequence key={i} from={b.start} durationInFrames={dur}>
            <KenBurnsImage src={b.src} dur={dur} move={b.move} intensity={b.intensity}
              fadeIn={i === 0 ? 0 : 12} />
          </Sequence>
        );
      })}
      <Sequence from={0} durationInFrames={150}>
        <AbsoluteFill style={{ justifyContent: 'center', alignItems: 'center', background: 'rgba(6,8,12,0.6)' }}>
          <div style={{ textAlign: 'center', padding: '0 120px' }}>
            <div style={{ fontFamily: 'Inter, sans-serif', fontWeight: 800, fontSize: 26,
                            letterSpacing: 6, color: ACCENT, textTransform: 'uppercase', marginBottom: 20 }}>Documentary</div>
            <div style={{ fontFamily: 'Inter, sans-serif', fontWeight: 900, fontSize: 88,
                            letterSpacing: 1, color: '#f4f2ee', lineHeight: 1.1 }}>{TITLE}</div>
          </div>
        </AbsoluteFill>
      </Sequence>
      {CHAPTERS.map((c, i) => (
        <Sequence key={'c' + i} from={c.from} durationInFrames={c.end - c.from}>
          <ChapterCard title={c.title} dur={c.end - c.from} />
        </Sequence>
      ))}
      <Captions lines={VO} y={930} size={38} accent={ACCENT} maxWords={7} plate />
      <ProgressBar color={ACCENT} />
    </AbsoluteFill>
  );
};

export default LongThesilent401Ktrapdra;
