import React from 'react';
import { AbsoluteFill, OffthreadVideo, Sequence, staticFile } from 'remotion';
import { Captions, ProgressBar } from '../../lib/shorts';
import { KenBurnsImage, StoryVignette } from '../../lib/story';
import { VO } from './vo.gen';

// =============================================================================
// AUTO-GENERATED by tools/make_short.py — "A 10-Billion-Trillion-Trillion-Carat Diamond Star"
// Camera moves + intensity follow the beat grammar (calm -> building -> payoff).
// motion:true beats use real AI video when FAL is configured, Ken Burns otherwise.
// =============================================================================
export const compositionConfig = {
  id: 'AutoA10Billiontrilliontr',
  durationInSeconds: 39.53,
  fps: 30,
  width: 1080,
  height: 1920,
};

const ACCENT = '#7dd3fc';
const TAIL = 20; // frames each beat under-laps the next so the crossfade never gaps

const BEATS = [
  { src: 'projects/auto-16-the-white-dwarf-star-turning-int/b00-hook.nasa.jpg', start: 0, end: 143, move: 'push-in', intensity: 0.5, clip: null, fadeIn: 0 },
  { src: 'projects/auto-16-the-white-dwarf-star-turning-int/b01-hook.jpg', start: 143, end: 234, move: 'crash-zoom', intensity: 0.5, clip: null, fadeIn: 14 },
  { src: 'projects/auto-16-the-white-dwarf-star-turning-int/b02-setup.nasa.jpg', start: 234, end: 383, move: 'pull-back', intensity: 0.7, clip: null, fadeIn: 14 },
  { src: 'projects/auto-16-the-white-dwarf-star-turning-int/b03-setup.nasa.jpg', start: 383, end: 521, move: 'drift-down', intensity: 0.75, clip: null, fadeIn: 14 },
  { src: 'projects/auto-16-the-white-dwarf-star-turning-int/b04-quiz.jpg', start: 521, end: 669, move: 'orbit-left', intensity: 0.75, clip: null, fadeIn: 14 },
  { src: 'projects/auto-16-the-white-dwarf-star-turning-int/b05-reveal.nasa.jpg', start: 669, end: 807, move: 'crash-zoom', intensity: 1.2, clip: null, fadeIn: 14 },
  { src: 'projects/auto-16-the-white-dwarf-star-turning-int/b06-twist.jpg', start: 807, end: 898, move: 'orbit-right', intensity: 1.15, clip: null, fadeIn: 14 },
  { src: 'projects/auto-16-the-white-dwarf-star-turning-int/b07-twist.nasa.jpg', start: 898, end: 1059, move: 'drift-up', intensity: 1.15, clip: null, fadeIn: 14 },
  { src: 'projects/auto-16-the-white-dwarf-star-turning-int/b08-loop.nasa.jpg', start: 1059, end: 1186, move: 'settle', intensity: 0.7, clip: null, fadeIn: 14 },
] as const;

const AutoA10Billiontrilliontr: React.FC = () => {
  return (
    <AbsoluteFill style={{ background: '#0b0d12' }}>
      {BEATS.map((b, i) => {
        const isLast = i === BEATS.length - 1;
        const dur = b.end - b.start + (isLast ? 0 : TAIL);
        return (
          <Sequence key={i} from={b.start} durationInFrames={dur}>
            {b.clip ? (
              <OffthreadVideo src={staticFile(b.clip)} muted
                style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
            ) : (
              <KenBurnsImage src={b.src} dur={dur} move={b.move}
                intensity={b.intensity} fadeIn={b.fadeIn} />
            )}
          </Sequence>
        );
      })}
      <StoryVignette strength={0.34} />
      <Captions lines={VO} y={1330} size={54} accent={ACCENT} maxWords={5} plate />
      <ProgressBar color={ACCENT} />
    </AbsoluteFill>
  );
};

export default AutoA10Billiontrilliontr;
