import React from 'react';
import { AbsoluteFill, OffthreadVideo, Sequence, staticFile } from 'remotion';
import { Captions, ProgressBar } from '../../lib/shorts';
import { KenBurnsImage, StoryVignette } from '../../lib/story';
import { VO } from './vo.gen';

// =============================================================================
// AUTO-GENERATED by tools/make_short.py — "The Solar Storm That Fried the World in 1859"
// Camera moves + intensity follow the beat grammar (calm -> building -> payoff).
// motion:true beats use real AI video when FAL is configured, Ken Burns otherwise.
// =============================================================================
export const compositionConfig = {
  id: 'AutoThesolarstormthatfri',
  durationInSeconds: 40.81,
  fps: 30,
  width: 1080,
  height: 1920,
};

const ACCENT = '#fda4af';
const TAIL = 20; // frames each beat under-laps the next so the crossfade never gaps

const BEATS = [
  { src: 'projects/auto-8-the-1859-solar-storm-that-caused/b00-hook.nasa.jpg', start: 0, end: 119, move: 'push-in', intensity: 0.5, clip: null, fadeIn: 0 },
  { src: 'projects/auto-8-the-1859-solar-storm-that-caused/b01-hook.nasa.jpg', start: 119, end: 242, move: 'crash-zoom', intensity: 0.5, clip: null, fadeIn: 14 },
  { src: 'projects/auto-8-the-1859-solar-storm-that-caused/b02-setup.nasa.jpg', start: 242, end: 366, move: 'drift-up', intensity: 0.69, clip: null, fadeIn: 14 },
  { src: 'projects/auto-8-the-1859-solar-storm-that-caused/b03-setup.nasa.jpg', start: 366, end: 479, move: 'push-in', intensity: 0.73, clip: null, fadeIn: 14 },
  { src: 'projects/auto-8-the-1859-solar-storm-that-caused/b04-quiz.nasa.jpg', start: 479, end: 624, move: 'orbit-left', intensity: 0.75, clip: null, fadeIn: 14 },
  { src: 'projects/auto-8-the-1859-solar-storm-that-caused/b05-reveal.nasa.jpg', start: 624, end: 726, move: 'crash-zoom', intensity: 1.2, clip: null, fadeIn: 14 },
  { src: 'projects/auto-8-the-1859-solar-storm-that-caused/b06-reveal.nasa.jpg', start: 726, end: 860, move: 'pan-right', intensity: 1.2, clip: null, fadeIn: 14 },
  { src: 'projects/auto-8-the-1859-solar-storm-that-caused/b07-twist.nasa.jpg', start: 860, end: 984, move: 'drift-down', intensity: 1.15, clip: null, fadeIn: 14 },
  { src: 'projects/auto-8-the-1859-solar-storm-that-caused/b08-twist.nasa.jpg', start: 984, end: 1118, move: 'pull-back', intensity: 1.15, clip: null, fadeIn: 14 },
  { src: 'projects/auto-8-the-1859-solar-storm-that-caused/b09-loop.nasa.jpg', start: 1118, end: 1224, move: 'settle', intensity: 0.7, clip: null, fadeIn: 14 },
] as const;

const AutoThesolarstormthatfri: React.FC = () => {
  return (
    <AbsoluteFill style={{ background: '#0b0d12' }}>
      {BEATS.map((b, i) => {
        const isLast = i === BEATS.length - 1;
        const dur = b.end - b.start + (isLast ? 0 : TAIL);
        return (
          <Sequence key={i} from={b.start} durationInFrames={dur}>
            {b.clip ? (
              <OffthreadVideo src={staticFile(b.clip)} muted
                style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
            ) : (
              <KenBurnsImage src={b.src} dur={dur} move={b.move}
                intensity={b.intensity} fadeIn={b.fadeIn} />
            )}
          </Sequence>
        );
      })}
      <StoryVignette strength={0.34} />
      <Captions lines={VO} y={1330} size={54} accent={ACCENT} maxWords={5} plate />
      <ProgressBar color={ACCENT} />
    </AbsoluteFill>
  );
};

export default AutoThesolarstormthatfri;
