import React from 'react';
import { AbsoluteFill, OffthreadVideo, Sequence, staticFile } from 'remotion';
import { Captions, ProgressBar } from '../../lib/shorts';
import { KenBurnsImage, StoryVignette } from '../../lib/story';
import { VO } from './vo.gen';

// =============================================================================
// AUTO-GENERATED by tools/make_short.py — "The $10,000 Quadrillion Asteroid"
// Camera moves + intensity follow the beat grammar (calm -> building -> payoff).
// motion:true beats use real AI video when FAL is configured, Ken Burns otherwise.
// =============================================================================
export const compositionConfig = {
  id: 'AutoThe10000Quadrilliona',
  durationInSeconds: 39.53,
  fps: 30,
  width: 1080,
  height: 1920,
};

const ACCENT = '#f5d76e';
const TAIL = 20; // frames each beat under-laps the next so the crossfade never gaps

const BEATS = [
  { src: 'projects/auto-10-the-asteroid-made-entirely-of-go/b00-hook.nasa.jpg', start: 0, end: 155, move: 'push-in', intensity: 0.5, clip: null, fadeIn: 0 },
  { src: 'projects/auto-10-the-asteroid-made-entirely-of-go/b01-setup.nasa.jpg', start: 155, end: 269, move: 'drift-up', intensity: 0.65, clip: null, fadeIn: 14 },
  { src: 'projects/auto-10-the-asteroid-made-entirely-of-go/b02-setup.jpg', start: 269, end: 406, move: 'orbit-left', intensity: 0.7, clip: null, fadeIn: 14 },
  { src: 'projects/auto-10-the-asteroid-made-entirely-of-go/b03-quiz.nasa.jpg', start: 406, end: 555, move: 'settle', intensity: 0.75, clip: null, fadeIn: 14 },
  { src: 'projects/auto-10-the-asteroid-made-entirely-of-go/b04-reveal.nasa.jpg', start: 555, end: 658, move: 'crash-zoom', intensity: 1.2, clip: null, fadeIn: 14 },
  { src: 'projects/auto-10-the-asteroid-made-entirely-of-go/b05-reveal.nasa.jpg', start: 658, end: 807, move: 'pull-back', intensity: 1.2, clip: null, fadeIn: 14 },
  { src: 'projects/auto-10-the-asteroid-made-entirely-of-go/b06-twist.nasa.jpg', start: 807, end: 968, move: 'pan-right', intensity: 1.15, clip: null, fadeIn: 14 },
  { src: 'projects/auto-10-the-asteroid-made-entirely-of-go/b07-twist.nasa.jpg', start: 968, end: 1070, move: 'drift-down', intensity: 1.15, clip: null, fadeIn: 14 },
  { src: 'projects/auto-10-the-asteroid-made-entirely-of-go/b08-loop.nasa.jpg', start: 1070, end: 1186, move: 'orbit-right', intensity: 0.7, clip: null, fadeIn: 14 },
] as const;

const AutoThe10000Quadrilliona: React.FC = () => {
  return (
    <AbsoluteFill style={{ background: '#0b0d12' }}>
      {BEATS.map((b, i) => {
        const isLast = i === BEATS.length - 1;
        const dur = b.end - b.start + (isLast ? 0 : TAIL);
        return (
          <Sequence key={i} from={b.start} durationInFrames={dur}>
            {b.clip ? (
              <OffthreadVideo src={staticFile(b.clip)} muted
                style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
            ) : (
              <KenBurnsImage src={b.src} dur={dur} move={b.move}
                intensity={b.intensity} fadeIn={b.fadeIn} />
            )}
          </Sequence>
        );
      })}
      <StoryVignette strength={0.34} />
      <Captions lines={VO} y={1330} size={54} accent={ACCENT} maxWords={5} plate />
      <ProgressBar color={ACCENT} />
    </AbsoluteFill>
  );
};

export default AutoThe10000Quadrilliona;
