import React from 'react';
import { AbsoluteFill, OffthreadVideo, Sequence, staticFile } from 'remotion';
import { Captions, ProgressBar } from '../../lib/shorts';
import { KenBurnsImage, StoryVignette } from '../../lib/story';
import { Transition } from '../../lib/transitions';
import { VO } from './vo.gen';

// =============================================================================
// AUTO-GENERATED by tools/make_short.py — "We Audio-Recorded Touching the Sun"
// Camera moves + intensity follow the beat grammar (calm -> building -> payoff).
// motion:true beats use archival/AI video when available, Ken Burns otherwise.
// The reveal gets a lens-flare bloom, the twist a whip-pan; numbers/dates
// highlighted in captions.
// =============================================================================
export const compositionConfig = {
  id: 'AutoWeaudiorecordedtouchi',
  durationInSeconds: 34.88,
  fps: 30,
  width: 1080,
  height: 1920,
};

const ACCENT = '#a78bfa';
const TAIL = 20; // frames each beat under-laps the next so the crossfade never gaps

const BEATS = [
  { src: 'projects/auto-8-the-sound-recorded-when-a-spacec/b00-hook.nasa.jpg', start: 0, end: 108, move: 'crash-zoom', intensity: 0.5, clip: null, fadeIn: 0 },
  { src: 'projects/auto-8-the-sound-recorded-when-a-spacec/b01-setup.nasa.jpg', start: 108, end: 234, move: 'push-in', intensity: 0.64, clip: null, fadeIn: 14 },
  { src: 'projects/auto-8-the-sound-recorded-when-a-spacec/b02-setup.nasa.jpg', start: 234, end: 314, move: 'orbit-left', intensity: 0.69, clip: null, fadeIn: 14 },
  { src: 'projects/auto-8-the-sound-recorded-when-a-spacec/b03-quiz.nasa.jpg', start: 314, end: 405, move: 'settle', intensity: 0.75, clip: null, fadeIn: 14 },
  { src: 'projects/auto-8-the-sound-recorded-when-a-spacec/b04-quiz.nasa.jpg', start: 405, end: 485, move: 'push-in', intensity: 0.75, clip: null, fadeIn: 14 },
  { src: 'projects/auto-8-the-sound-recorded-when-a-spacec/b05-reveal.nasa.jpg', start: 485, end: 611, move: 'crash-zoom', intensity: 1.2, clip: null, fadeIn: 14 },
  { src: 'projects/auto-8-the-sound-recorded-when-a-spacec/b06-reveal.nasa.jpg', start: 611, end: 714, move: 'orbit-right', intensity: 1.2, clip: null, fadeIn: 14 },
  { src: 'projects/auto-8-the-sound-recorded-when-a-spacec/b07-twist.nasa.jpg', start: 714, end: 816, move: 'drift-up', intensity: 1.15, clip: null, fadeIn: 14 },
  { src: 'projects/auto-8-the-sound-recorded-when-a-spacec/b08-twist.nasa.jpg', start: 816, end: 966, move: 'push-in', intensity: 1.15, clip: null, fadeIn: 14 },
  { src: 'projects/auto-8-the-sound-recorded-when-a-spacec/b09-loop.nasa.jpg', start: 966, end: 1046, move: 'pull-back', intensity: 0.7, clip: null, fadeIn: 14 },
] as const;

const TRANSITIONS = [
  { kind: 'flare', at: 485, dur: 8 },
  { kind: 'flare', at: 611, dur: 8 },
  { kind: 'whip-pan', at: 714, dur: 8 },
  { kind: 'whip-pan', at: 816, dur: 8 },
] as const;

const AutoWeaudiorecordedtouchi: React.FC = () => {
  return (
    <AbsoluteFill style={{ background: '#0b0d12' }}>
      {BEATS.map((b, i) => {
        const isLast = i === BEATS.length - 1;
        const dur = b.end - b.start + (isLast ? 0 : TAIL);
        return (
          <Sequence key={i} from={b.start} durationInFrames={dur}>
            {b.clip ? (
              <OffthreadVideo src={staticFile(b.clip)} muted
                style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
            ) : (
              <KenBurnsImage src={b.src} dur={dur} move={b.move}
                intensity={b.intensity} fadeIn={b.fadeIn} />
            )}
          </Sequence>
        );
      })}
      <StoryVignette strength={0.34} />
      {TRANSITIONS.map((t, i) => (
        <Sequence key={'t' + i} from={Math.max(0, t.at - 4)} durationInFrames={t.dur}>
          <Transition kind={t.kind} dur={t.dur} accent={ACCENT} />
        </Sequence>
      ))}
      <Captions lines={VO} y={1330} size={54} accent={ACCENT} maxWords={5} plate highlight />
      <ProgressBar color={ACCENT} />
    </AbsoluteFill>
  );
};

export default AutoWeaudiorecordedtouchi;
