import React from 'react';
import { AbsoluteFill, OffthreadVideo, Sequence, staticFile } from 'remotion';
import { Captions, ProgressBar } from '../../lib/shorts';
import { KenBurnsImage, StoryVignette } from '../../lib/story';
import { VO } from './vo.gen';

// =============================================================================
// AUTO-GENERATED by tools/make_short.py — "The Planet Where Metal Rains From Sky"
// Camera moves + intensity follow the beat grammar (calm -> building -> payoff).
// motion:true beats use real AI video when FAL is configured, Ken Burns otherwise.
// =============================================================================
export const compositionConfig = {
  id: 'AutoTheplanetwheremetalr',
  durationInSeconds: 40.85,
  fps: 30,
  width: 1080,
  height: 1920,
};

const ACCENT = '#a78bfa';
const TAIL = 20; // frames each beat under-laps the next so the crossfade never gaps

const BEATS = [
  { src: 'projects/auto-22-the-planet-640-light-years-away/b00-hook.nasa.jpg', start: 0, end: 119, move: 'push-in', intensity: 0.5, clip: null, fadeIn: 0 },
  { src: 'projects/auto-22-the-planet-640-light-years-away/b01-setup.nasa.jpg', start: 119, end: 245, move: 'orbit-left', intensity: 0.64, clip: null, fadeIn: 14 },
  { src: 'projects/auto-22-the-planet-640-light-years-away/b02-setup.nasa.jpg', start: 245, end: 358, move: 'drift-up', intensity: 0.69, clip: null, fadeIn: 14 },
  { src: 'projects/auto-22-the-planet-640-light-years-away/b03-setup.nasa.jpg', start: 358, end: 484, move: 'push-in', intensity: 0.73, clip: null, fadeIn: 14 },
  { src: 'projects/auto-22-the-planet-640-light-years-away/b04-quiz.nasa.jpg', start: 484, end: 597, move: 'settle', intensity: 0.75, clip: null, fadeIn: 14 },
  { src: 'projects/auto-22-the-planet-640-light-years-away/b05-reveal.nasa.jpg', start: 597, end: 734, move: 'crash-zoom', intensity: 1.2, clip: null, fadeIn: 14 },
  { src: 'projects/auto-22-the-planet-640-light-years-away/b06-reveal.jpg', start: 734, end: 860, move: 'drift-down', intensity: 1.2, clip: null, fadeIn: 14 },
  { src: 'projects/auto-22-the-planet-640-light-years-away/b07-twist.jpg', start: 860, end: 996, move: 'pull-back', intensity: 1.15, clip: null, fadeIn: 14 },
  { src: 'projects/auto-22-the-planet-640-light-years-away/b08-twist.nasa.jpg', start: 996, end: 1133, move: 'orbit-right', intensity: 1.15, clip: null, fadeIn: 14 },
  { src: 'projects/auto-22-the-planet-640-light-years-away/b09-loop.nasa.jpg', start: 1133, end: 1226, move: 'push-in', intensity: 0.7, clip: null, fadeIn: 14 },
] as const;

const AutoTheplanetwheremetalr: React.FC = () => {
  return (
    <AbsoluteFill style={{ background: '#0b0d12' }}>
      {BEATS.map((b, i) => {
        const isLast = i === BEATS.length - 1;
        const dur = b.end - b.start + (isLast ? 0 : TAIL);
        return (
          <Sequence key={i} from={b.start} durationInFrames={dur}>
            {b.clip ? (
              <OffthreadVideo src={staticFile(b.clip)} muted
                style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
            ) : (
              <KenBurnsImage src={b.src} dur={dur} move={b.move}
                intensity={b.intensity} fadeIn={b.fadeIn} />
            )}
          </Sequence>
        );
      })}
      <StoryVignette strength={0.34} />
      <Captions lines={VO} y={1330} size={54} accent={ACCENT} maxWords={5} plate />
      <ProgressBar color={ACCENT} />
    </AbsoluteFill>
  );
};

export default AutoTheplanetwheremetalr;
