import React from 'react';
import { AbsoluteFill, OffthreadVideo, Sequence, staticFile } from 'remotion';
import { Captions, ProgressBar } from '../../lib/shorts';
import { KenBurnsImage, StoryVignette } from '../../lib/story';
import { VO } from './vo.gen';

// =============================================================================
// AUTO-GENERATED by tools/make_short.py — "The Moon Is Shrinking and Cracking Open"
// Camera moves + intensity follow the beat grammar (calm -> building -> payoff).
// motion:true beats use real AI video when FAL is configured, Ken Burns otherwise.
// =============================================================================
export const compositionConfig = {
  id: 'AutoThemoonisshrinkingan',
  durationInSeconds: 40.3,
  fps: 30,
  width: 1080,
  height: 1920,
};

const ACCENT = '#86efac';
const TAIL = 20; // frames each beat under-laps the next so the crossfade never gaps

const BEATS = [
  { src: 'projects/auto-14-the-moon-is-shrinking-and-it-is/b00-hook.jpg', start: 0, end: 143, move: 'crash-zoom', intensity: 0.5, clip: null, fadeIn: 0 },
  { src: 'projects/auto-14-the-moon-is-shrinking-and-it-is/b01-setup.nasa.jpg', start: 143, end: 269, move: 'pull-back', intensity: 0.65, clip: null, fadeIn: 14 },
  { src: 'projects/auto-14-the-moon-is-shrinking-and-it-is/b02-setup.nasa.jpg', start: 269, end: 418, move: 'orbit-right', intensity: 0.7, clip: null, fadeIn: 14 },
  { src: 'projects/auto-14-the-moon-is-shrinking-and-it-is/b03-quiz.nasa.jpg', start: 418, end: 544, move: 'settle', intensity: 0.75, clip: null, fadeIn: 14 },
  { src: 'projects/auto-14-the-moon-is-shrinking-and-it-is/b04-reveal.nasa.jpg', start: 544, end: 692, move: 'push-in', intensity: 1.2, clip: null, fadeIn: 14 },
  { src: 'projects/auto-14-the-moon-is-shrinking-and-it-is/b05-reveal.nasa.jpg', start: 692, end: 842, move: 'pan-left', intensity: 1.2, clip: null, fadeIn: 14 },
  { src: 'projects/auto-14-the-moon-is-shrinking-and-it-is/b06-twist.nasa.jpg', start: 842, end: 979, move: 'drift-up', intensity: 1.15, clip: null, fadeIn: 14 },
  { src: 'projects/auto-14-the-moon-is-shrinking-and-it-is/b07-twist.nasa.jpg', start: 979, end: 1116, move: 'push-in', intensity: 1.15, clip: null, fadeIn: 14 },
  { src: 'projects/auto-14-the-moon-is-shrinking-and-it-is/b08-loop.jpg', start: 1116, end: 1209, move: 'push-in', intensity: 0.7, clip: null, fadeIn: 14 },
] as const;

const AutoThemoonisshrinkingan: React.FC = () => {
  return (
    <AbsoluteFill style={{ background: '#0b0d12' }}>
      {BEATS.map((b, i) => {
        const isLast = i === BEATS.length - 1;
        const dur = b.end - b.start + (isLast ? 0 : TAIL);
        return (
          <Sequence key={i} from={b.start} durationInFrames={dur}>
            {b.clip ? (
              <OffthreadVideo src={staticFile(b.clip)} muted
                style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
            ) : (
              <KenBurnsImage src={b.src} dur={dur} move={b.move}
                intensity={b.intensity} fadeIn={b.fadeIn} />
            )}
          </Sequence>
        );
      })}
      <StoryVignette strength={0.34} />
      <Captions lines={VO} y={1330} size={54} accent={ACCENT} maxWords={5} plate />
      <ProgressBar color={ACCENT} />
    </AbsoluteFill>
  );
};

export default AutoThemoonisshrinkingan;
