import React from 'react';
import { AbsoluteFill, OffthreadVideo, Sequence, staticFile } from 'remotion';
import { Captions, ProgressBar } from '../../lib/shorts';
import { KenBurnsImage, StoryVignette } from '../../lib/story';
import { VO } from './vo.gen';

// =============================================================================
// AUTO-GENERATED by tools/make_short.py — "The Ocean Floating in Deep Space Around a Quasar"
// Camera moves + intensity follow the beat grammar (calm -> building -> payoff).
// motion:true beats use real AI video when FAL is configured, Ken Burns otherwise.
// =============================================================================
export const compositionConfig = {
  id: 'AutoTheoceanfloatinginde',
  durationInSeconds: 40.82,
  fps: 30,
  width: 1080,
  height: 1920,
};

const ACCENT = '#a78bfa';
const TAIL = 20; // frames each beat under-laps the next so the crossfade never gaps

const BEATS = [
  { src: 'projects/auto-12-the-100-trillion-ton-water-ocean/b00-hook.nasa.jpg', start: 0, end: 101, move: 'push-in', intensity: 0.5, clip: null, fadeIn: 0 },
  { src: 'projects/auto-12-the-100-trillion-ton-water-ocean/b01-hook.nasa.jpg', start: 101, end: 206, move: 'pull-back', intensity: 0.5, clip: null, fadeIn: 14 },
  { src: 'projects/auto-12-the-100-trillion-ton-water-ocean/b02-setup.nasa.jpg', start: 206, end: 322, move: 'orbit-right', intensity: 0.69, clip: null, fadeIn: 14 },
  { src: 'projects/auto-12-the-100-trillion-ton-water-ocean/b03-setup.nasa.jpg', start: 322, end: 449, move: 'drift-up', intensity: 0.73, clip: null, fadeIn: 14 },
  { src: 'projects/auto-12-the-100-trillion-ton-water-ocean/b04-quiz.nasa.jpg', start: 449, end: 555, move: 'settle', intensity: 0.75, clip: null, fadeIn: 14 },
  { src: 'projects/auto-12-the-100-trillion-ton-water-ocean/b05-reveal.nasa.jpg', start: 555, end: 692, move: 'crash-zoom', intensity: 1.2, clip: null, fadeIn: 14 },
  { src: 'projects/auto-12-the-100-trillion-ton-water-ocean/b06-reveal.nasa.jpg', start: 692, end: 819, move: 'drift-down', intensity: 1.2, clip: null, fadeIn: 14 },
  { src: 'projects/auto-12-the-100-trillion-ton-water-ocean/b07-twist.nasa.jpg', start: 819, end: 968, move: 'orbit-left', intensity: 1.15, clip: null, fadeIn: 14 },
  { src: 'projects/auto-12-the-100-trillion-ton-water-ocean/b08-twist.nasa.jpg', start: 968, end: 1094, move: 'pan-right', intensity: 1.15, clip: null, fadeIn: 14 },
  { src: 'projects/auto-12-the-100-trillion-ton-water-ocean/b09-loop.jpg', start: 1094, end: 1225, move: 'push-in', intensity: 0.7, clip: null, fadeIn: 14 },
] as const;

const AutoTheoceanfloatinginde: React.FC = () => {
  return (
    <AbsoluteFill style={{ background: '#0b0d12' }}>
      {BEATS.map((b, i) => {
        const isLast = i === BEATS.length - 1;
        const dur = b.end - b.start + (isLast ? 0 : TAIL);
        return (
          <Sequence key={i} from={b.start} durationInFrames={dur}>
            {b.clip ? (
              <OffthreadVideo src={staticFile(b.clip)} muted
                style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
            ) : (
              <KenBurnsImage src={b.src} dur={dur} move={b.move}
                intensity={b.intensity} fadeIn={b.fadeIn} />
            )}
          </Sequence>
        );
      })}
      <StoryVignette strength={0.34} />
      <Captions lines={VO} y={1330} size={54} accent={ACCENT} maxWords={5} plate />
      <ProgressBar color={ACCENT} />
    </AbsoluteFill>
  );
};

export default AutoTheoceanfloatinginde;
