import React from 'react';
import { AbsoluteFill, OffthreadVideo, Sequence, staticFile } from 'remotion';
import { Captions, ProgressBar } from '../../lib/shorts';
import { KenBurnsImage, StoryVignette } from '../../lib/story';
import { VO } from './vo.gen';

// =============================================================================
// AUTO-GENERATED by tools/make_short.py — "Ancient Tree Rings Expose a 774 AD Space Disaster"
// Camera moves + intensity follow the beat grammar (calm -> building -> payoff).
// motion:true beats use real AI video when FAL is configured, Ken Burns otherwise.
// =============================================================================
export const compositionConfig = {
  id: 'AutoAncienttreeringsexpos',
  durationInSeconds: 40.81,
  fps: 30,
  width: 1080,
  height: 1920,
};

const ACCENT = '#fda4af';
const TAIL = 20; // frames each beat under-laps the next so the crossfade never gaps

const BEATS = [
  { src: 'projects/auto-18-the-ancient-tree-rings-that-prov/b00-hook.nasa.jpg', start: 0, end: 128, move: 'push-in', intensity: 0.5, clip: null, fadeIn: 0 },
  { src: 'projects/auto-18-the-ancient-tree-rings-that-prov/b01-hook.nasa.jpg', start: 128, end: 251, move: 'crash-zoom', intensity: 0.5, clip: null, fadeIn: 14 },
  { src: 'projects/auto-18-the-ancient-tree-rings-that-prov/b02-setup.nasa.jpg', start: 251, end: 384, move: 'orbit-left', intensity: 0.69, clip: null, fadeIn: 14 },
  { src: 'projects/auto-18-the-ancient-tree-rings-that-prov/b03-setup.nasa.jpg', start: 384, end: 506, move: 'push-in', intensity: 0.73, clip: null, fadeIn: 14 },
  { src: 'projects/auto-18-the-ancient-tree-rings-that-prov/b04-quiz.nasa.jpg', start: 506, end: 628, move: 'settle', intensity: 0.75, clip: null, fadeIn: 14 },
  { src: 'projects/auto-18-the-ancient-tree-rings-that-prov/b05-reveal.nasa.jpg', start: 628, end: 740, move: 'crash-zoom', intensity: 1.2, clip: null, fadeIn: 14 },
  { src: 'projects/auto-18-the-ancient-tree-rings-that-prov/b06-reveal.nasa.jpg', start: 740, end: 873, move: 'orbit-right', intensity: 1.2, clip: null, fadeIn: 14 },
  { src: 'projects/auto-18-the-ancient-tree-rings-that-prov/b07-twist.nasa.jpg', start: 873, end: 975, move: 'drift-down', intensity: 1.15, clip: null, fadeIn: 14 },
  { src: 'projects/auto-18-the-ancient-tree-rings-that-prov/b08-twist.nasa.jpg', start: 975, end: 1108, move: 'pan-right', intensity: 1.15, clip: null, fadeIn: 14 },
  { src: 'projects/auto-18-the-ancient-tree-rings-that-prov/b09-loop.nasa.jpg', start: 1108, end: 1224, move: 'push-in', intensity: 0.7, clip: null, fadeIn: 14 },
] as const;

const AutoAncienttreeringsexpos: React.FC = () => {
  return (
    <AbsoluteFill style={{ background: '#0b0d12' }}>
      {BEATS.map((b, i) => {
        const isLast = i === BEATS.length - 1;
        const dur = b.end - b.start + (isLast ? 0 : TAIL);
        return (
          <Sequence key={i} from={b.start} durationInFrames={dur}>
            {b.clip ? (
              <OffthreadVideo src={staticFile(b.clip)} muted
                style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
            ) : (
              <KenBurnsImage src={b.src} dur={dur} move={b.move}
                intensity={b.intensity} fadeIn={b.fadeIn} />
            )}
          </Sequence>
        );
      })}
      <StoryVignette strength={0.34} />
      <Captions lines={VO} y={1330} size={54} accent={ACCENT} maxWords={5} plate />
      <ProgressBar color={ACCENT} />
    </AbsoluteFill>
  );
};

export default AutoAncienttreeringsexpos;
