import React from 'react';
import { AbsoluteFill, Sequence } from 'remotion';
import { Captions, ProgressBar } from '../../lib/shorts';
import { KenBurnsImage, StoryVignette } from '../../lib/story';
import { VO } from './vo.gen';

// =============================================================================
// AUTO-GENERATED by tools/make_short.py — "The Planet Where It Rains Glass Sideways"
// Ken Burns beat images + word-pop captions + progress bar. Local pipeline:
// local-AI script -> Pollinations images -> Kokoro voice -> this render.
// =============================================================================
export const compositionConfig = {
  id: 'AutoTheplanetwhereitrain',
  durationInSeconds: 40.84,
  fps: 30,
  width: 1080,
  height: 1920,
};

const ACCENT = '#a78bfa';
const TAIL = 20; // frames each beat under-laps the next so the crossfade never gaps

const BEATS = [
  { src: 'projects/auto-2-the-planet-where-it-rains-molten/b00-hook.jpg', start: 6, end: 170, variant: 0, fadeIn: 0 },
  { src: 'projects/auto-2-the-planet-where-it-rains-molten/b01-setup.jpg', start: 170, end: 313, variant: 1, fadeIn: 14 },
  { src: 'projects/auto-2-the-planet-where-it-rains-molten/b02-setup.jpg', start: 313, end: 444, variant: 2, fadeIn: 14 },
  { src: 'projects/auto-2-the-planet-where-it-rains-molten/b03-quiz.jpg', start: 444, end: 587, variant: 3, fadeIn: 14 },
  { src: 'projects/auto-2-the-planet-where-it-rains-molten/b04-reveal.jpg', start: 587, end: 740, variant: 4, fadeIn: 14 },
  { src: 'projects/auto-2-the-planet-where-it-rains-molten/b05-reveal.jpg', start: 740, end: 872, variant: 5, fadeIn: 14 },
  { src: 'projects/auto-2-the-planet-where-it-rains-molten/b06-twist.jpg', start: 872, end: 1015, variant: 0, fadeIn: 14 },
  { src: 'projects/auto-2-the-planet-where-it-rains-molten/b07-twist.jpg', start: 1015, end: 1158, variant: 1, fadeIn: 14 },
  { src: 'projects/auto-2-the-planet-where-it-rains-molten/b08-loop.jpg', start: 1158, end: 1225, variant: 2, fadeIn: 14 },
] as const;

const AutoTheplanetwhereitrain: React.FC = () => {
  return (
    <AbsoluteFill style={{ background: '#0b0d12' }}>
      {BEATS.map((b, i) => {
        const isLast = i === BEATS.length - 1;
        const dur = b.end - b.start + (isLast ? 0 : TAIL);
        return (
          <Sequence key={i} from={b.start} durationInFrames={dur}>
            <KenBurnsImage src={b.src} dur={dur} variant={b.variant} fadeIn={b.fadeIn} />
          </Sequence>
        );
      })}
      <StoryVignette strength={0.34} />
      <Captions lines={VO} y={1330} size={54} accent={ACCENT} maxWords={4} plate />
      <ProgressBar color={ACCENT} />
    </AbsoluteFill>
  );
};

export default AutoTheplanetwhereitrain;
