import React from 'react';
import { AbsoluteFill, OffthreadVideo, Sequence, staticFile } from 'remotion';
import { Captions, ProgressBar } from '../../lib/shorts';
import { KenBurnsImage, StoryVignette } from '../../lib/story';
import { VO } from './vo.gen';

// =============================================================================
// AUTO-GENERATED by tools/make_short.py — "The 330 Million Light-Year Void in Space"
// Camera moves + intensity follow the beat grammar (calm -> building -> payoff).
// motion:true beats use real AI video when FAL is configured, Ken Burns otherwise.
// =============================================================================
export const compositionConfig = {
  id: 'AutoThe330Millionlightye',
  durationInSeconds: 32.61,
  fps: 30,
  width: 1080,
  height: 1920,
};

const ACCENT = '#86efac';
const TAIL = 20; // frames each beat under-laps the next so the crossfade never gaps

const BEATS = [
  { src: 'projects/auto-9-the-void-in-space-that-is-330-mi/b00-hook.jpg', start: 0, end: 97, move: 'push-in', intensity: 0.5, clip: null, fadeIn: 0 },
  { src: 'projects/auto-9-the-void-in-space-that-is-330-mi/b01-hook.jpg', start: 97, end: 188, move: 'orbit-left', intensity: 0.5, clip: null, fadeIn: 14 },
  { src: 'projects/auto-9-the-void-in-space-that-is-330-mi/b02-setup.nasa.jpg', start: 188, end: 291, move: 'pull-back', intensity: 0.7, clip: null, fadeIn: 14 },
  { src: 'projects/auto-9-the-void-in-space-that-is-330-mi/b03-setup.nasa.jpg', start: 291, end: 405, move: 'drift-up', intensity: 0.75, clip: null, fadeIn: 14 },
  { src: 'projects/auto-9-the-void-in-space-that-is-330-mi/b04-quiz.nasa.jpg', start: 405, end: 508, move: 'settle', intensity: 0.75, clip: null, fadeIn: 14 },
  { src: 'projects/auto-9-the-void-in-space-that-is-330-mi/b05-reveal.nasa.jpg', start: 508, end: 576, move: 'crash-zoom', intensity: 1.2, clip: null, fadeIn: 14 },
  { src: 'projects/auto-9-the-void-in-space-that-is-330-mi/b06-twist.nasa.jpg', start: 576, end: 725, move: 'push-in', intensity: 1.15, clip: null, fadeIn: 14 },
  { src: 'projects/auto-9-the-void-in-space-that-is-330-mi/b07-twist.nasa.jpg', start: 725, end: 851, move: 'pan-right', intensity: 1.15, clip: null, fadeIn: 14 },
  { src: 'projects/auto-9-the-void-in-space-that-is-330-mi/b08-loop.jpg', start: 851, end: 978, move: 'pull-back', intensity: 0.7, clip: null, fadeIn: 14 },
] as const;

const AutoThe330Millionlightye: React.FC = () => {
  return (
    <AbsoluteFill style={{ background: '#0b0d12' }}>
      {BEATS.map((b, i) => {
        const isLast = i === BEATS.length - 1;
        const dur = b.end - b.start + (isLast ? 0 : TAIL);
        return (
          <Sequence key={i} from={b.start} durationInFrames={dur}>
            {b.clip ? (
              <OffthreadVideo src={staticFile(b.clip)} muted
                style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
            ) : (
              <KenBurnsImage src={b.src} dur={dur} move={b.move}
                intensity={b.intensity} fadeIn={b.fadeIn} />
            )}
          </Sequence>
        );
      })}
      <StoryVignette strength={0.34} />
      <Captions lines={VO} y={1330} size={54} accent={ACCENT} maxWords={5} plate />
      <ProgressBar color={ACCENT} />
    </AbsoluteFill>
  );
};

export default AutoThe330Millionlightye;
