import React from 'react';
import { AbsoluteFill, OffthreadVideo, Sequence, staticFile } from 'remotion';
import { Captions, ProgressBar } from '../../lib/shorts';
import { KenBurnsImage, StoryVignette } from '../../lib/story';
import { VO } from './vo.gen';

// =============================================================================
// AUTO-GENERATED by tools/make_short.py — "The Cosmic Ray That Shattered Physics"
// Camera moves + intensity follow the beat grammar (calm -> building -> payoff).
// motion:true beats use real AI video when FAL is configured, Ken Burns otherwise.
// =============================================================================
export const compositionConfig = {
  id: 'AutoThecosmicraythatshat',
  durationInSeconds: 40.3,
  fps: 30,
  width: 1080,
  height: 1920,
};

const ACCENT = '#a78bfa';
const TAIL = 20; // frames each beat under-laps the next so the crossfade never gaps

const BEATS = [
  { src: 'projects/auto-17-the-cosmic-particle-that-hit-ear/b00-hook.nasa.jpg', start: 0, end: 143, move: 'crash-zoom', intensity: 0.5, clip: null, fadeIn: 0 },
  { src: 'projects/auto-17-the-cosmic-particle-that-hit-ear/b01-hook.nasa.jpg', start: 143, end: 257, move: 'push-in', intensity: 0.5, clip: null, fadeIn: 14 },
  { src: 'projects/auto-17-the-cosmic-particle-that-hit-ear/b02-setup.nasa.jpg', start: 257, end: 383, move: 'drift-down', intensity: 0.7, clip: null, fadeIn: 14 },
  { src: 'projects/auto-17-the-cosmic-particle-that-hit-ear/b03-setup.jpg', start: 383, end: 509, move: 'orbit-left', intensity: 0.75, clip: null, fadeIn: 14 },
  { src: 'projects/auto-17-the-cosmic-particle-that-hit-ear/b04-quiz.nasa.jpg', start: 509, end: 635, move: 'settle', intensity: 0.75, clip: null, fadeIn: 14 },
  { src: 'projects/auto-17-the-cosmic-particle-that-hit-ear/b05-reveal.nasa.jpg', start: 635, end: 772, move: 'crash-zoom', intensity: 1.2, clip: null, fadeIn: 14 },
  { src: 'projects/auto-17-the-cosmic-particle-that-hit-ear/b06-twist.nasa.jpg', start: 772, end: 910, move: 'pull-back', intensity: 1.15, clip: null, fadeIn: 14 },
  { src: 'projects/auto-17-the-cosmic-particle-that-hit-ear/b07-twist.nasa.jpg', start: 910, end: 1047, move: 'orbit-right', intensity: 1.15, clip: null, fadeIn: 14 },
  { src: 'projects/auto-17-the-cosmic-particle-that-hit-ear/b08-loop.nasa.jpg', start: 1047, end: 1209, move: 'push-in', intensity: 0.7, clip: null, fadeIn: 14 },
] as const;

const AutoThecosmicraythatshat: React.FC = () => {
  return (
    <AbsoluteFill style={{ background: '#0b0d12' }}>
      {BEATS.map((b, i) => {
        const isLast = i === BEATS.length - 1;
        const dur = b.end - b.start + (isLast ? 0 : TAIL);
        return (
          <Sequence key={i} from={b.start} durationInFrames={dur}>
            {b.clip ? (
              <OffthreadVideo src={staticFile(b.clip)} muted
                style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
            ) : (
              <KenBurnsImage src={b.src} dur={dur} move={b.move}
                intensity={b.intensity} fadeIn={b.fadeIn} />
            )}
          </Sequence>
        );
      })}
      <StoryVignette strength={0.34} />
      <Captions lines={VO} y={1330} size={54} accent={ACCENT} maxWords={5} plate />
      <ProgressBar color={ACCENT} />
    </AbsoluteFill>
  );
};

export default AutoThecosmicraythatshat;
