import React from 'react';
import { AbsoluteFill, OffthreadVideo, Sequence, staticFile } from 'remotion';
import { Captions, ProgressBar } from '../../lib/shorts';
import { ArchivalImage, HookCard } from '../../lib/archival';
import { Transition } from '../../lib/transitions';
import { VO } from './vo.gen';

// =============================================================================
// AUTO-GENERATED by tools/make_short.py (HISTORY edit format) — "The 2mm Design Change That Killed 114 People"
// EVIDENCE FIRST: archival imagery, film grade + grain, date/source stamps,
// editorial wipes between scenes, numbers/dates highlighted in captions.
// Real archive hits carry their own credit; AI fallbacks are labeled as such.
// =============================================================================
export const compositionConfig = {
  id: 'AutoThe2Mmdesignchangeth',
  durationInSeconds: 40.84,
  fps: 30,
  width: 1080,
  height: 1920,
};

const ACCENT = '#a78bfa';
const TAIL = 20;

const BEATS = [
  { src: 'projects/hist-1-the-1981-hyatt-regency-skywalk-c/b00-hook.arch.jpg', start: 0, end: 67, move: 'push-in', intensity: 0.5, clip: null, fadeIn: 0 },
  { src: 'projects/hist-1-the-1981-hyatt-regency-skywalk-c/b00-hook-b.jpg', start: 67, end: 148, move: 'pan-right', intensity: 0.42, clip: null, fadeIn: 0 },
  { src: 'projects/hist-1-the-1981-hyatt-regency-skywalk-c/b01-setup.arch.jpg', start: 148, end: 217, move: 'drift-up', intensity: 0.65, clip: null, fadeIn: 14 },
  { src: 'projects/hist-1-the-1981-hyatt-regency-skywalk-c/b01-setup-b.jpg', start: 217, end: 302, move: 'pan-right', intensity: 0.55, clip: null, fadeIn: 0 },
  { src: 'projects/hist-1-the-1981-hyatt-regency-skywalk-c/b02-setup.arch.jpg', start: 302, end: 356, move: 'pan-right', intensity: 0.7, clip: null, fadeIn: 14 },
  { src: 'projects/hist-1-the-1981-hyatt-regency-skywalk-c/b02-setup-b.jpg', start: 356, end: 422, move: 'pull-back', intensity: 0.59, clip: null, fadeIn: 0 },
  { src: 'projects/hist-1-the-1981-hyatt-regency-skywalk-c/b03-quiz.arch.jpg', start: 422, end: 476, move: 'settle', intensity: 0.75, clip: null, fadeIn: 14 },
  { src: 'projects/hist-1-the-1981-hyatt-regency-skywalk-c/b03-quiz-b.jpg', start: 476, end: 543, move: 'pan-right', intensity: 0.64, clip: null, fadeIn: 0 },
  { src: 'projects/hist-1-the-1981-hyatt-regency-skywalk-c/b04-reveal.arch.jpg', start: 543, end: 612, move: 'crash-zoom', intensity: 1.2, clip: null, fadeIn: 14 },
  { src: 'projects/hist-1-the-1981-hyatt-regency-skywalk-c/b04-reveal-b.jpg', start: 612, end: 696, move: 'settle', intensity: 1.02, clip: null, fadeIn: 0 },
  { src: 'projects/hist-1-the-1981-hyatt-regency-skywalk-c/b05-reveal.arch.jpg', start: 696, end: 755, move: 'push-in', intensity: 1.2, clip: null, fadeIn: 14 },
  { src: 'projects/hist-1-the-1981-hyatt-regency-skywalk-c/b05-reveal-b.jpg', start: 755, end: 828, move: 'pan-right', intensity: 1.02, clip: null, fadeIn: 0 },
  { src: 'projects/hist-1-the-1981-hyatt-regency-skywalk-c/b06-twist.arch.jpg', start: 828, end: 887, move: 'orbit-left', intensity: 1.15, clip: null, fadeIn: 14 },
  { src: 'projects/hist-1-the-1981-hyatt-regency-skywalk-c/b06-twist-b.jpg', start: 887, end: 959, move: 'drift-up', intensity: 0.98, clip: null, fadeIn: 0 },
  { src: 'projects/hist-1-the-1981-hyatt-regency-skywalk-c/b07-twist.arch.jpg', start: 959, end: 1018, move: 'pull-back', intensity: 1.15, clip: null, fadeIn: 14 },
  { src: 'projects/hist-1-the-1981-hyatt-regency-skywalk-c/b07-twist-b.jpg', start: 1018, end: 1091, move: 'pan-left', intensity: 0.98, clip: null, fadeIn: 0 },
  { src: 'projects/hist-1-the-1981-hyatt-regency-skywalk-c/b08-loop.arch.jpg', start: 1091, end: 1151, move: 'push-in', intensity: 0.7, clip: null, fadeIn: 14 },
  { src: 'projects/hist-1-the-1981-hyatt-regency-skywalk-c/b08-loop-b.jpg', start: 1151, end: 1225, move: 'pan-right', intensity: 0.59, clip: null, fadeIn: 0 },
] as const;

const TAGS = [
  { tag: "JULY 17, 1981", source: "Wikimedia Commons \u00b7 1981", from: 0, end: 67 },
  { tag: "JULY 17, 1981", source: "Wikimedia Commons \u00b7 1981", from: 67, end: 148 },
  { tag: "KANSAS CITY, MO", source: "Wikimedia Commons \u00b7 1982", from: 148, end: 217 },
  { tag: "KANSAS CITY, MO", source: "Wikimedia Commons \u00b7 1982", from: 217, end: 302 },
  { tag: "HYATT REGENCY ATRIUM", source: "Wikimedia Commons \u00b7 1981", from: 302, end: 356 },
  { tag: "HYATT REGENCY ATRIUM", source: "Wikimedia Commons \u00b7 1981", from: 356, end: 422 },
  { tag: "PAUSE AND THINK", source: "Wikimedia Commons \u00b7 2026", from: 422, end: 476 },
  { tag: "PAUSE AND THINK", source: "Wikimedia Commons \u00b7 2026", from: 476, end: 543 },
  { tag: "ENGINEERING DIAGRAM", source: "Wikimedia Commons \u00b7 2013", from: 543, end: 612 },
  { tag: "ENGINEERING DIAGRAM", source: "Wikimedia Commons \u00b7 2013", from: 612, end: 696 },
  { tag: "LOAD PATH DOUBLED", source: "Wikimedia Commons \u00b7 1981", from: 696, end: 755 },
  { tag: "LOAD PATH DOUBLED", source: "Wikimedia Commons \u00b7 1981", from: 755, end: 828 },
  { tag: "NIST INVESTIGATION", source: "Wikimedia Commons \u00b7 1980", from: 828, end: 887 },
  { tag: "NIST INVESTIGATION", source: "Wikimedia Commons \u00b7 1980", from: 887, end: 959 },
  { tag: "114 FATALITIES", source: "Wikimedia Commons \u00b7 2025", from: 959, end: 1018 },
  { tag: "114 FATALITIES", source: "Wikimedia Commons \u00b7 2025", from: 1018, end: 1091 },
  { tag: "JULY 17, 1981", source: "Met Museum \u00b7 1790", from: 1091, end: 1151 },
  { tag: "JULY 17, 1981", source: "Met Museum \u00b7 1790", from: 1151, end: 1225 },
] as const;

const TRANSITIONS = [
  { kind: 'wipe', at: 148, dur: 8, label: "KANSAS CITY, MO" },
  { kind: 'whip-pan', at: 302, dur: 8, label: "" },
  { kind: 'glitch', at: 422, dur: 8, label: "" },
  { kind: 'rewind', at: 543, dur: 8, label: "" },
  { kind: 'rewind', at: 696, dur: 8, label: "" },
  { kind: 'wipe', at: 828, dur: 8, label: "NIST INVESTIGATION" },
  { kind: 'wipe', at: 959, dur: 8, label: "114 FATALITIES" },
  { kind: 'whip-pan', at: 1091, dur: 8, label: "" },
] as const;

const HOOK_CARD = "A _2MM_ fatal MISTAKE";
const HOOK_END = 148;

const AutoThe2Mmdesignchangeth: React.FC = () => {
  return (
    <AbsoluteFill style={{ background: '#0b0a08' }}>
      {BEATS.map((b, i) => {
        const isLast = i === BEATS.length - 1;
        const dur = b.end - b.start + (isLast ? 0 : TAIL);
        const tag = TAGS[i] || {};
        return (
          <Sequence key={i} from={b.start} durationInFrames={dur}>
            {b.clip ? (
              <OffthreadVideo src={staticFile(b.clip)} muted
                style={{ width: '100%', height: '100%', objectFit: 'cover',
                  filter: 'sepia(0.28) contrast(1.06) brightness(0.94)' }} />
            ) : (
              <ArchivalImage src={b.src} dur={dur} move={b.move}
                intensity={b.intensity} fadeIn={b.fadeIn}
                tag={tag.tag} source={tag.source} />
            )}
          </Sequence>
        );
      })}
      <Sequence from={0} durationInFrames={HOOK_END + 20}>
        <HookCard text={HOOK_CARD} accent={ACCENT} />
      </Sequence>
      {TRANSITIONS.map((t, i) => (
        <Sequence key={'t' + i} from={Math.max(0, t.at - 4)} durationInFrames={t.dur}>
          <Transition kind={t.kind} dur={t.dur} accent={ACCENT} label={t.label} />
        </Sequence>
      ))}
      <Captions lines={VO} y={1330} size={54} accent={ACCENT} maxWords={5} plate highlight />
      <ProgressBar color={ACCENT} />
    </AbsoluteFill>
  );
};

export default AutoThe2Mmdesignchangeth;
